#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/../.." && pwd)"
workspace_root="$(cd "${repo_root}/.." && pwd)"
docker_dir="${repo_root}/.dev/docker"
compose_file="${docker_dir}/compose.yaml"
defaults_file="${docker_dir}/defaults.env"
local_file="${docker_dir}/local.env"
runtime_dir="${repo_root}/.dev/runtime"
runtime_env="${runtime_dir}/test.env"
sqlite_file="${runtime_dir}/sqlite/prismgo_test.sqlite"

compose_args=(--project-directory "${repo_root}" --env-file "${defaults_file}")
if [[ -f "${local_file}" ]]; then
    compose_args+=(--env-file "${local_file}")
fi
compose_args+=(-f "${compose_file}")

all_services=(mysql postgres sqlserver redis rabbitmq)

usage() {
    cat <<'EOF'
PrismGo local test environment

Usage: ./dev/dev <command> [arguments]

Commands:
  init                  Initialize workspace links and clone missing repositories
  up [service...]       Start all services, or only the named services
  down                  Stop services and retain their data
  status                Show service health and local connection details
  logs [service]        Follow logs for all services or one service
  env                   Regenerate and print the test environment file
  test [go-test-args]   Start dependencies and run framework integration tests
  doctor                Check local prerequisites and render Compose config
  reset [--yes]         Delete all local test data and recreate the environment
  help                  Show this help

Services: mysql postgres sqlserver redis rabbitmq sqlite
EOF
}

compose() {
    docker compose "${compose_args[@]}" "$@"
}

require_docker() {
    if ! command -v docker >/dev/null 2>&1; then
        echo "Docker is required but was not found in PATH." >&2
        exit 1
    fi
    if ! docker compose version >/dev/null 2>&1; then
        echo "Docker Compose v2 is required (docker compose)." >&2
        exit 1
    fi
    if ! docker info >/dev/null 2>&1; then
        echo "The Docker daemon is not available to the current user." >&2
        exit 1
    fi
}

load_environment() {
    set -a
    # shellcheck disable=SC1090
    source "${defaults_file}"
    if [[ -f "${local_file}" ]]; then
        # shellcheck disable=SC1090
        source "${local_file}"
    fi
    set +a
}

prepare_runtime() {
    load_environment
    mkdir -p "$(dirname "${sqlite_file}")"
    touch "${sqlite_file}"

    {
        printf '# Generated by ./dev/dev env. Do not edit; override dev/.dev/docker/local.env instead.\n'
        printf 'export PRISMGO_MYSQL_TEST_DSN=%q\n' "${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(127.0.0.1:${MYSQL_PORT})/${MYSQL_DATABASE}?charset=utf8mb4&parseTime=true&loc=Local"
        printf 'export PRISMGO_SQLITE_TEST_DSN=%q\n' "file:${sqlite_file}?cache=shared"
        printf 'export PRISMGO_POSTGRES_TEST_DSN=%q\n' "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:${POSTGRES_PORT}/${POSTGRES_DATABASE}?sslmode=disable"
        printf 'export PRISMGO_SQLSERVER_TEST_DSN=%q\n' "sqlserver://sa:${SQLSERVER_SA_PASSWORD}@127.0.0.1:${SQLSERVER_PORT}?database=${SQLSERVER_DATABASE}&encrypt=disable"
        printf 'export PRISMGO_REDIS_TEST_ADDR=%q\n' "127.0.0.1:${REDIS_PORT}"
        printf 'export PRISMGO_REDIS_TEST_URL=%q\n' "redis://127.0.0.1:${REDIS_PORT}/0"
        printf 'export PRISMGO_RABBITMQ_TEST_URL=%q\n' "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@127.0.0.1:${RABBITMQ_PORT}/%2F"
    } >"${runtime_env}"
}

validate_services() {
    local service candidate found
    for service in "$@"; do
        if [[ "${service}" == "sqlite" ]]; then
            continue
        fi
        found=false
        for candidate in "${all_services[@]}"; do
            if [[ "${service}" == "${candidate}" ]]; then
                found=true
                break
            fi
        done
        if [[ "${found}" != true ]]; then
            echo "Unknown service: ${service}" >&2
            usage >&2
            exit 2
        fi
    done
}

up_environment() {
    prepare_runtime

    local requested=("$@")
    if [[ ${#requested[@]} -eq 0 ]]; then
        requested=("${all_services[@]}")
    fi
    validate_services "${requested[@]}"

    local compose_services=() service sqlserver_requested=false
    for service in "${requested[@]}"; do
        if [[ "${service}" != "sqlite" ]]; then
            compose_services+=("${service}")
        fi
        if [[ "${service}" == "sqlserver" ]]; then
            sqlserver_requested=true
        fi
    done

    if [[ ${#compose_services[@]} -gt 0 ]]; then
        require_docker
        compose up -d --wait --wait-timeout 240 "${compose_services[@]}"
    fi
    if [[ "${sqlserver_requested}" == true ]]; then
        compose --profile tools run --rm sqlserver-init
    fi

    echo
    echo "PrismGo test environment is ready."
    print_connections
}

print_connections() {
    prepare_runtime
    load_environment
    cat <<EOF
MySQL:       127.0.0.1:${MYSQL_PORT} (${MYSQL_DATABASE}, ${MYSQL_USER}/${MYSQL_PASSWORD})
PostgreSQL:  127.0.0.1:${POSTGRES_PORT} (${POSTGRES_DATABASE}, ${POSTGRES_USER}/${POSTGRES_PASSWORD})
SQL Server:  127.0.0.1:${SQLSERVER_PORT} (${SQLSERVER_DATABASE}, sa/${SQLSERVER_SA_PASSWORD})
SQLite:      ${sqlite_file}
Redis:       127.0.0.1:${REDIS_PORT}
RabbitMQ:    127.0.0.1:${RABBITMQ_PORT} (${RABBITMQ_USER}/${RABBITMQ_PASSWORD})
RabbitMQ UI: http://127.0.0.1:${RABBITMQ_MANAGEMENT_PORT}
Listen on:   ${BIND_ADDRESS} (LAN clients use this host's LAN IP and the same ports)
Environment: ${runtime_env}
EOF
}

run_tests() {
    up_environment
    # shellcheck disable=SC1090
    source "${runtime_env}"
    if [[ $# -eq 0 ]]; then
        set -- ./queue/... ./horizon/...
    fi
    cd "${workspace_root}/framework"
    go test "$@"
}

doctor() {
    require_docker
    prepare_runtime
    echo "Docker:  $(docker --version)"
    echo "Compose: $(docker compose version --short)"
    echo "Host:     $(uname -s)/$(uname -m)"
    if [[ "$(uname -m)" == "arm64" || "$(uname -m)" == "aarch64" ]]; then
        echo "Notice: SQL Server is configured as linux/amd64 and may run through emulation."
    fi
    compose config --quiet
    echo "Compose configuration: valid"
    echo "Runtime environment:   ${runtime_env}"
}

reset_environment() {
    local confirmed=false
    if [[ "${1:-}" == "--yes" ]]; then
        confirmed=true
    elif [[ -t 0 ]]; then
        read -r -p "Delete all PrismGo test databases and queues? [y/N] " answer
        if [[ "${answer}" == "y" || "${answer}" == "Y" ]]; then
            confirmed=true
        fi
    fi
    if [[ "${confirmed}" != true ]]; then
        echo "Reset cancelled. Pass --yes for non-interactive use."
        return 1
    fi
    require_docker
    compose down --volumes --remove-orphans
    rm -f "${sqlite_file}"
    up_environment
}

command="${1:-help}"
if [[ $# -gt 0 ]]; then
    shift
fi

case "${command}" in
    up)
        up_environment "$@"
        ;;
    down)
        require_docker
        compose down --remove-orphans
        ;;
    status)
        require_docker
        compose ps --all
        echo
        print_connections
        ;;
    logs)
        require_docker
        if [[ $# -gt 1 ]]; then
            echo "logs accepts at most one service name" >&2
            exit 2
        fi
        if [[ $# -eq 1 ]]; then
            validate_services "$1"
            if [[ "$1" == "sqlite" ]]; then
                echo "SQLite is an in-process file database and has no container logs."
                exit 0
            fi
            compose logs --follow "$1"
        else
            compose logs --follow
        fi
        ;;
    env)
        prepare_runtime
        cat "${runtime_env}"
        ;;
    test)
        run_tests "$@"
        ;;
    doctor)
        doctor
        ;;
    reset)
        reset_environment "$@"
        ;;
    help|-h|--help)
        usage
        ;;
    *)
        echo "Unknown command: ${command}" >&2
        usage >&2
        exit 2
        ;;
esac
