package catalog

func cacheEntries() []Entry {
	return []Entry{
		baselineEntry("cache", "Manager and repository architecture", "简介", "Introduction", "demo:cache architecture", "architecture", "TestCacheDemoArchitecture", LevelCompile, StatusImplemented),
		baselineEntry("cache", "Configuration loading", "配置文件", "Config File", "demo:cache config", "config", "TestCacheDemoConfiguration", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Driver prerequisites", "驱动前置条件", "Driver Prerequisites", "demo:cache driver-prerequisites", "driver-prerequisites", "TestCacheDemoDriverPrerequisites", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Top-level configuration", "顶层配置", "Top-Level Configuration", "demo:cache top-level-config", "top-level-config", "TestCacheDemoTopLevelConfiguration", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Memory store configuration", "Memory Store", "Memory Store", "demo:cache memory-config", "memory-config", "TestCacheDemoMemoryConfiguration", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Redis store configuration", "Redis Store", "Redis Store", "demo:cache redis-config", "redis-config", "TestCacheDemoRedisConfiguration", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "File store configuration", "File Store", "File Store", "demo:cache file-config", "file-config", "TestCacheDemoFileConfiguration", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Failover store configuration", "Failover Store", "Failover Store", "demo:cache failover-config", "failover-config", "TestCacheDemoFailoverConfiguration", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Lock configuration", "锁配置", "Lock Configuration", "demo:cache lock-config", "lock-config", "TestCacheDemoLockConfiguration", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Flexible refresh configuration", "热点刷新配置", "Hot Key Refresh Configuration", "demo:cache flexible-config", "flexible-config", "TestCacheDemoFlexibleConfiguration", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Package-level facade", "使用包级 Facade", "Using the Package-Level Facade", "demo:cache facade", "facade", "TestCacheDemoFacade", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Named store operations", "使用指定 Store", "Using a Specific Store", "demo:cache named-store", "named-store", "TestCacheDemoNamedStore", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Repository dependency injection", "获取 Repository 实例", "Obtaining a Repository Instance", "demo:cache repository", "repository", "TestCacheDemoRepository", LevelCompile, StatusImplemented),
		baselineEntry("cache", "Missing named store errors", "获取缓存实例", "Obtaining a Cache Instance", "demo:cache missing-store", "missing-store", "TestCacheDemoMissingStore", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Generic retrieval and cache misses", "基础读取", "Basic Retrieval", "demo:cache get", "get", "TestCacheDemoGet", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Value and lazy fallbacks", "带默认值读取", "Retrieval with Default Value", "demo:cache fallbacks", "fallbacks", "TestCacheDemoFallbacks", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Typed convenience retrieval", "便捷类型读取", "Typed Convenience Methods", "demo:cache typed-retrieval", "typed-retrieval", "TestCacheDemoTypedRetrieval", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Cache key existence", "判断存在性", "Checking Existence", "demo:cache existence", "existence", "TestCacheDemoExistence", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Put and Set storage", "基础写入", "Basic Storage", "demo:cache put", "put", "TestCacheDemoPutAndSet", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Permanent storage", "永久写入", "Permanent Storage", "demo:cache forever", "forever", "TestCacheDemoForever", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Atomic conditional storage", "条件写入（仅当 key 不存在）", "Conditional Storage (Write Only If Key Does Not Exist)", "demo:cache add", "add", "TestCacheDemoAdd", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Bulk storage aliases", "批量写入", "Bulk Storage", "demo:cache put-many", "put-many", "TestCacheDemoPutMany", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Retrieve and store", "读穿缓存（Remember）", "Retrieve and Store", "demo:cache remember", "remember", "TestCacheDemoRemember", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Permanent retrieve and store aliases", "永久读穿", "Remember Forever", "demo:cache remember-forever", "remember-forever", "TestCacheDemoRememberForever", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Stale-while-revalidate windows", "Stale-While-Revalidate（Flexible）", "Stale-While-Revalidate (Flexible)", "demo:cache flexible", "flexible", "TestCacheDemoFlexible", LevelScenario, StatusImplemented),
		baselineEntry("cache", "Touch TTL semantics", "延长 TTL", "Touch TTL", "demo:cache touch", "touch", "TestCacheDemoTouch", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Bulk retrieval aliases", "批量读取", "Retrieving Multiple Items", "demo:cache many", "many", "TestCacheDemoMany", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Atomic retrieve and delete", "取后删除", "Retrieve and Delete", "demo:cache pull", "pull", "TestCacheDemoPull", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Single-key removal aliases", "删除单个 key", "Removing a Single Key", "demo:cache forget", "forget", "TestCacheDemoForget", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Bulk removal", "批量删除", "Bulk Removal", "demo:cache forget-many", "forget-many", "TestCacheDemoForgetMany", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Store flush aliases and prefix safety", "清空整个 store", "Clearing an Entire Store", "demo:cache flush", "flush", "TestCacheDemoFlush", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Atomic integer counters", "计数器", "Counters", "demo:cache counters", "counters", "TestCacheDemoCounters", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Lock acquisition and release", "基础用法", "Basic Usage", "demo:cache lock", "lock", "TestCacheDemoLock", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Lock callback auto-release", "回调自动释放", "Automatic Release via Callback", "demo:cache lock-callback", "lock-callback", "TestCacheDemoLockCallback", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Blocking lock wait and timeout", "阻塞等待", "Blocking Wait", "demo:cache lock-block", "lock-block", "TestCacheDemoLockBlock", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Lock owner restoration and force release", "跨流程释放", "Cross-Process Release", "demo:cache lock-restore", "lock-restore", "TestCacheDemoLockRestore", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Lock namespace cleanup", "批量清理锁", "Bulk Lock Cleanup", "demo:cache lock-flush", "lock-flush", "TestCacheDemoLockFlush", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Funnel concurrency limiting", "并发限制器（Funnel）", "Concurrency Limiter (Funnel)", "demo:cache funnel", "funnel", "TestCacheDemoFunnel", LevelScenario, StatusImplemented),
		baselineEntry("cache", "Overlapping task prevention", "防止任务重叠（WithoutOverlapping）", "Preventing Task Overlap (WithoutOverlapping)", "demo:cache without-overlapping", "without-overlapping", "TestCacheDemoWithoutOverlapping", LevelScenario, StatusImplemented),
		baselineEntry("cache", "Memory tagged cache", "Tagged Cache", "Tagged Cache", "demo:cache tags-memory", "tags-memory", "TestCacheDemoMemoryTags", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Redis tagged cache", "Tagged Cache", "Tagged Cache", "demo:cache tags-redis", "tags-redis", "TestCacheDemoRedisTags", LevelIntegration, StatusImplemented, "redis"),
		baselineEntry("cache", "Unsupported tagged cache", "Tagged Cache", "Tagged Cache", "demo:cache tags-unsupported", "tags-unsupported", "TestCacheDemoUnsupportedTags", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Request-scoped memoization", "Memoization", "Memoization", "demo:cache memo", "memo", "TestCacheDemoMemo", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Failover behavior and events", "Failover", "Failover", "demo:cache failover", "failover", "TestCacheDemoFailover", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Custom driver registration and capabilities", "自定义 Driver", "Custom Drivers", "demo:cache custom-driver", "custom-driver", "TestCacheDemoCustomDriver", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Manager resource lifecycle", "资源生命周期", "Resource Lifecycle", "demo:cache resource-lifecycle", "resource-lifecycle", "TestCacheDemoResourceLifecycle", LevelScenario, StatusImplemented),
		baselineEntry("cache", "Lifecycle event dispatch", "Cache Events", "Cache Events", "demo:cache events", "events", "TestCacheDemoEvents", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Cache event payload contract", "事件列表", "Event List", "demo:cache event-contract", "event-contract", "TestCacheDemoEventContract", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Deferred refresh context", "Deferred Context", "Deferred Context", "demo:cache deferred", "deferred", "TestCacheDemoDeferred", LevelScenario, StatusImplemented),
		baselineEntry("cache", "Cache and lock key prefixes", "Key 前缀", "Key Prefixes", "demo:cache key-prefixes", "key-prefixes", "TestCacheDemoKeyPrefixes", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Payload encoding conventions", "数据编码约定", "Data Encoding Conventions", "demo:cache encoding", "encoding", "TestCacheDemoEncoding", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Error constants", "错误常量", "Error Constants", "demo:cache errors", "errors", "TestCacheDemoErrors", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Memory store capability matrix", "内置 Store 能力矩阵", "Built-in Store Capability Matrix", "demo:cache memory-capabilities", "memory-capabilities", "TestCacheDemoMemoryCapabilities", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "File store capability matrix", "内置 Store 能力矩阵", "Built-in Store Capability Matrix", "demo:cache file-capabilities", "file-capabilities", "TestCacheDemoFileCapabilities", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Redis store capability matrix", "内置 Store 能力矩阵", "Built-in Store Capability Matrix", "demo:cache redis-capabilities", "redis-capabilities", "TestCacheDemoRedisCapabilities", LevelIntegration, StatusImplemented, "redis"),
		baselineEntry("cache", "Failover store capability matrix", "内置 Store 能力矩阵", "Built-in Store Capability Matrix", "demo:cache failover-capabilities", "failover-capabilities", "TestCacheDemoFailoverCapabilities", LevelHermetic, StatusImplemented),
		baselineEntry("cache", "Laravel cache API mapping", "与 Laravel Cache 的对应关系", "Laravel Cache Mapping", "demo:cache laravel-compatibility", "laravel-compatibility", "TestCacheDemoLaravelCompatibility", LevelCompile, StatusImplemented),
	}
}
