package catalog

func configEntries() []Entry {
	return []Entry{
		baselineEntry("config", "Register and read a mail configuration namespace", "快速开始", "Quick Start", "demo:config quick-start", "quick-start", "TestConfigDemoQuickStart", LevelScenario, StatusImplemented),
		baselineEntry("config", "Runtime configuration is static application data", "组件用途", "What It Is For", "demo:config runtime-scope", "runtime-scope", "TestConfigDemoRuntimeScope", LevelCompile, StatusImplemented),
		baselineEntry("config", "Application container lazily constructs the configuration repository", "加载流程", "Loading Flow", "demo:config lazy-loading", "lazy-loading", "TestConfigDemoLazyLoading", LevelScenario, StatusImplemented),
		baselineEntry("config", "Registration functions run when the repository is constructed", "加载流程", "Loading Flow", "demo:config registration-timing", "registration-timing", "TestConfigDemoRegistrationTiming", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Missing .env uses process environment and defaults", "加载流程", "Loading Flow", "demo:config missing-env-file", "missing-env-file", "TestConfigDemoMissingEnvFile", LevelHermetic, StatusImplemented),
		baselineEntry("config", ".env and process environment values override defaults", "加载流程", "Loading Flow", "demo:config env-precedence", "env-precedence", "TestConfigDemoEnvPrecedence", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Env reads a single environment variable", "环境变量函数", "Environment Variable Function", "demo:config env", "env", "TestConfigDemoEnv", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Env returns defaults for missing or blank values", "Env", "Env", "demo:config env-default", "env-default", "TestConfigDemoEnvDefault", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Env converts boolean values", "Env", "Env", "demo:config env-bool", "env-bool", "TestConfigDemoEnvBool", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Env converts int values", "Env", "Env", "demo:config env-int", "env-int", "TestConfigDemoEnvInt", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Env converts int64 values", "Env", "Env", "demo:config env-int64", "env-int64", "TestConfigDemoEnvInt64", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Env converts uint values", "Env", "Env", "demo:config env-uint", "env-uint", "TestConfigDemoEnvUint", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Env converts float64 values", "Env", "Env", "demo:config env-float64", "env-float64", "TestConfigDemoEnvFloat64", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Env returns string values", "Env", "Env", "demo:config env-string", "env-string", "TestConfigDemoEnvString", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Add registers a named configuration namespace", "配置注册", "Registering Configuration", "demo:config add", "add", "TestConfigDemoAdd", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Dot paths read nested registered values", "配置注册", "Registering Configuration", "demo:config nested-path", "nested-path", "TestConfigDemoNestedPath", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Nested registration maps normalize to map[string]any", "配置注册", "Registering Configuration", "demo:config map-normalization", "map-normalization", "TestConfigDemoMapNormalization", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Get and GetString read strings", "配置读取", "Reading Configuration", "demo:config get-string", "get-string", "TestConfigDemoGetString", LevelHermetic, StatusImplemented),
		baselineEntry("config", "GetInt reads integers", "配置读取", "Reading Configuration", "demo:config get-int", "get-int", "TestConfigDemoGetInt", LevelHermetic, StatusImplemented),
		baselineEntry("config", "GetInt64 reads 64-bit integers", "配置读取", "Reading Configuration", "demo:config get-int64", "get-int64", "TestConfigDemoGetInt64", LevelHermetic, StatusImplemented),
		baselineEntry("config", "GetUint reads unsigned integers", "配置读取", "Reading Configuration", "demo:config get-uint", "get-uint", "TestConfigDemoGetUint", LevelHermetic, StatusImplemented),
		baselineEntry("config", "GetFloat64 reads floating-point values", "配置读取", "Reading Configuration", "demo:config get-float64", "get-float64", "TestConfigDemoGetFloat64", LevelHermetic, StatusImplemented),
		baselineEntry("config", "GetBool reads booleans", "配置读取", "Reading Configuration", "demo:config get-bool", "get-bool", "TestConfigDemoGetBool", LevelHermetic, StatusImplemented),
		baselineEntry("config", "GetStringMap reads nested configuration blocks", "配置读取", "Reading Configuration", "demo:config get-string-map", "get-string-map", "TestConfigDemoGetStringMap", LevelHermetic, StatusImplemented),
		baselineEntry("config", "GetStringMapString reads string maps", "配置读取", "Reading Configuration", "demo:config get-string-map-string", "get-string-map-string", "TestConfigDemoGetStringMapString", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Typed getters use supplied defaults for missing paths", "配置读取", "Reading Configuration", "demo:config get-default", "get-default", "TestConfigDemoGetDefault", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Missing map paths return empty non-nil maps", "配置读取", "Reading Configuration", "demo:config missing-map", "missing-map", "TestConfigDemoMissingMap", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Application configuration is registered in config/app.go", "应用配置参考", "Application Configuration Reference", "demo:config app-registration", "app-registration", "TestConfigDemoAppRegistration", LevelCompile, StatusImplemented),
		baselineEntry("config", "app.name and APP_NAME", "基础应用配置", "Base Application Configuration", "demo:config app-name", "app-name", "TestConfigDemoAppName", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.env and APP_ENV", "基础应用配置", "Base Application Configuration", "demo:config app-env", "app-env", "TestConfigDemoAppEnv", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.key and APP_KEY", "基础应用配置", "Base Application Configuration", "demo:config app-key", "app-key", "TestConfigDemoAppKey", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.debug and APP_DEBUG", "基础应用配置", "Base Application Configuration", "demo:config app-debug", "app-debug", "TestConfigDemoAppDebug", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.url and APP_URL", "基础应用配置", "Base Application Configuration", "demo:config app-url", "app-url", "TestConfigDemoAppURL", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.timezone and APP_TIMEZONE", "基础应用配置", "Base Application Configuration", "demo:config app-timezone", "app-timezone", "TestConfigDemoAppTimezone", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.locale and APP_LOCALE", "基础应用配置", "Base Application Configuration", "demo:config app-locale", "app-locale", "TestConfigDemoAppLocale", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.fallback_locale and APP_FALLBACK_LOCALE", "基础应用配置", "Base Application Configuration", "demo:config app-fallback-locale", "app-fallback-locale", "TestConfigDemoAppFallbackLocale", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.cipher and APP_CIPHER", "基础应用配置", "Base Application Configuration", "demo:config app-cipher", "app-cipher", "TestConfigDemoAppCipher", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.previous_keys and APP_PREVIOUS_KEYS", "基础应用配置", "Base Application Configuration", "demo:config app-previous-keys", "app-previous-keys", "TestConfigDemoAppPreviousKeys", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.server.host and SERVER_HOST", "HTTP Server 配置", "HTTP Server Configuration", "demo:config server-host", "server-host", "TestConfigDemoServerHost", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.server.port and SERVER_PORT", "HTTP Server 配置", "HTTP Server Configuration", "demo:config server-port", "server-port", "TestConfigDemoServerPort", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.server.timeout and SERVER_TIMEOUT", "HTTP Server 配置", "HTTP Server Configuration", "demo:config server-timeout", "server-timeout", "TestConfigDemoServerTimeout", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.server.read_timeout and SERVER_READ_TIMEOUT", "HTTP Server 配置", "HTTP Server Configuration", "demo:config server-read-timeout", "server-read-timeout", "TestConfigDemoServerReadTimeout", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.server.read_header_timeout and SERVER_READ_HEADER_TIMEOUT", "HTTP Server 配置", "HTTP Server Configuration", "demo:config server-read-header-timeout", "server-read-header-timeout", "TestConfigDemoServerReadHeaderTimeout", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.server.write_timeout and SERVER_WRITE_TIMEOUT", "HTTP Server 配置", "HTTP Server Configuration", "demo:config server-write-timeout", "server-write-timeout", "TestConfigDemoServerWriteTimeout", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.server.idle_timeout and SERVER_IDLE_TIMEOUT", "HTTP Server 配置", "HTTP Server Configuration", "demo:config server-idle-timeout", "server-idle-timeout", "TestConfigDemoServerIdleTimeout", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.server.shutdown_timeout and SERVER_SHUTDOWN_TIMEOUT", "HTTP Server 配置", "HTTP Server Configuration", "demo:config server-shutdown-timeout", "server-shutdown-timeout", "TestConfigDemoServerShutdownTimeout", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.server.max_header_bytes and SERVER_MAX_HEADER_BYTES", "HTTP Server 配置", "HTTP Server Configuration", "demo:config server-max-header-bytes", "server-max-header-bytes", "TestConfigDemoServerMaxHeaderBytes", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.server.max_multipart_memory and SERVER_MAX_MULTIPART_MEMORY", "HTTP Server 配置", "HTTP Server Configuration", "demo:config server-max-multipart-memory", "server-max-multipart-memory", "TestConfigDemoServerMaxMultipartMemory", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.server.trusted_proxies and SERVER_TRUSTED_PROXIES", "HTTP Server 配置", "HTTP Server Configuration", "demo:config server-trusted-proxies", "server-trusted-proxies", "TestConfigDemoServerTrustedProxies", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.server.client_ip_headers and SERVER_CLIENT_IP_HEADERS", "HTTP Server 配置", "HTTP Server Configuration", "demo:config server-client-ip-headers", "server-client-ip-headers", "TestConfigDemoServerClientIPHeaders", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.server.access_log and SERVER_ACCESS_LOG", "HTTP Server 配置", "HTTP Server Configuration", "demo:config server-access-log", "server-access-log", "TestConfigDemoServerAccessLog", LevelHermetic, StatusImplemented),
		baselineEntry("config", "app.server.exception_handler and SERVER_EXCEPTION_HANDLER", "HTTP Server 配置", "HTTP Server Configuration", "demo:config server-exception-handler", "server-exception-handler", "TestConfigDemoServerExceptionHandler", LevelHermetic, StatusImplemented),
		baselineEntry("config", "NewFromFile creates an isolated repository", "独立实例", "Standalone Instances", "demo:config new-from-file", "new-from-file", "TestConfigDemoNewFromFile", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Standalone repositories read typed values", "独立实例", "Standalone Instances", "demo:config standalone-read", "standalone-read", "TestConfigDemoStandaloneRead", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Clone isolates repositories from later reloads", "独立实例", "Standalone Instances", "demo:config clone-isolation", "clone-isolation", "TestConfigDemoCloneIsolation", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Resolve reads configuration from the current Application container", "facade 入口", "Facade Entry Points", "demo:config resolve", "resolve", "TestConfigDemoResolve", LevelScenario, StatusImplemented),
		baselineEntry("config", "Clone copies the current facade repository", "facade 入口", "Facade Entry Points", "demo:config facade-clone", "facade-clone", "TestConfigDemoFacadeClone", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Reload refreshes configuration from the default .env", "facade 入口", "Facade Entry Points", "demo:config reload", "reload", "TestConfigDemoReload", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Empty reports whether the current repository has values", "facade 入口", "Facade Entry Points", "demo:config empty", "empty", "TestConfigDemoEmpty", LevelHermetic, StatusImplemented),
		baselineEntry("config", "Tests bind an isolated configuration repository", "facade 入口", "Facade Entry Points", "demo:config test-binding", "test-binding", "TestConfigDemoTestBinding", LevelScenario, StatusImplemented),
		baselineEntry("config", "Configuration namespaces and environment variables follow application conventions", "使用建议", "Recommendations", "demo:config conventions", "conventions", "TestConfigDemoConventions", LevelCompile, StatusImplemented),
		baselineEntry("config", "Mutable business settings live outside runtime configuration", "使用建议", "Recommendations", "demo:config mutable-settings", "mutable-settings", "TestConfigDemoMutableSettings", LevelCompile, StatusImplemented),
	}
}
