package catalog

func cookieEntries() []Entry {
	return []Entry{
		baselineEntry("cookie", "Cookie value objects and request-scoped writes", "简介", "Introduction", "demo:cookie value-object", "value-object", "TestCookieDemoValueObject", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "Queue deduplication by name, path, and domain", "简介", "Introduction", "demo:cookie scope-deduplication", "scope-deduplication", "TestCookieDemoScopeDeduplication", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "Default path, HTTPOnly, Secure, SameSite, and forever lifetime", "默认值", "Default Values", "demo:cookie defaults", "defaults", "TestCookieDemoDefaults", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "Service provider lazy cookie.queue binding", "服务提供者", "Service Provider", "demo:cookie provider", "provider", "TestCookieDemoProvider", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "QueuedCookies request queue and response flush", "中间件", "Middleware", "demo:cookie middleware", "middleware", "TestCookieDemoMiddleware", LevelScenario, StatusPlanned),
		baselineEntry("cookie", "QueuedCookies flush failure response", "中间件", "Middleware", "demo:cookie flush-failure", "flush-failure", "TestCookieDemoFlushFailure", LevelScenario, StatusPlanned),
		baselineEntry("cookie", "StartSession installs the cookie queue", "中间件", "Middleware", "demo:cookie session-queue", "session-queue", "TestCookieDemoSessionQueue", LevelScenario, StatusPlanned),
		baselineEntry("cookie", "New and Make create unwritten Cookie values", "基础创建", "Basic Creation", "demo:cookie make", "make", "TestCookieDemoMake", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "Forever creates a long-lived Cookie", "长期 Cookie", "Forever Cookies", "demo:cookie forever", "forever", "TestCookieDemoForever", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "Path and Domain scope options", "构造参数与选项", "Constructor Parameters and Options", "demo:cookie scope-options", "scope-options", "TestCookieDemoScopeOptions", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "HTTPOnly and Secure options", "构造参数与选项", "Constructor Parameters and Options", "demo:cookie security-flags", "security-flags", "TestCookieDemoSecurityFlags", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "Raw value option", "构造参数与选项", "Constructor Parameters and Options", "demo:cookie raw", "raw", "TestCookieDemoRaw", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "Reusable ScopeOption", "构造参数与选项", "Constructor Parameters and Options", "demo:cookie scope-option", "scope-option", "TestCookieDemoScopeOption", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "Relative minutes and zero-minute expiry", "构造参数与选项", "Constructor Parameters and Options", "demo:cookie minutes", "minutes", "TestCookieDemoMinutes", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "ExpiresAt overrides relative expiry", "显式过期时间与 Max-Age", "Explicit Expiry Time and Max-Age", "demo:cookie expires-at", "expires-at", "TestCookieDemoExpiresAt", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "Explicit MaxAge and combined ExpiresAt output", "显式过期时间与 Max-Age", "Explicit Expiry Time and Max-Age", "demo:cookie max-age", "max-age", "TestCookieDemoMaxAge", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "Method and package-level Attach write Set-Cookie", "直接附加到响应", "Direct Attachment", "demo:cookie attach", "attach", "TestCookieDemoAttach", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "Invalid cookie name prevents response write", "直接附加到响应", "Direct Attachment", "demo:cookie invalid-name", "invalid-name", "TestCookieDemoInvalidName", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "WithContext propagates to security extensions", "Attach 选项", "Attach Options", "demo:cookie attach-context", "attach-context", "TestCookieDemoAttachContext", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "WithNow controls relative expiry calculation", "Attach 选项", "Attach Options", "demo:cookie attach-now", "attach-now", "TestCookieDemoAttachNow", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "QueueMakeFrom creates and queues a Cookie", "排队 Cookie", "Queuing Cookies", "demo:cookie queue-make", "queue-make", "TestCookieDemoQueueMake", LevelScenario, StatusPlanned),
		baselineEntry("cookie", "QueueForeverFrom queues a long-lived Cookie", "排队 Cookie", "Queuing Cookies", "demo:cookie queue-forever", "queue-forever", "TestCookieDemoQueueForever", LevelScenario, StatusPlanned),
		baselineEntry("cookie", "QueueCookieFrom queues a constructed value", "排队 Cookie", "Queuing Cookies", "demo:cookie queue-cookie", "queue-cookie", "TestCookieDemoQueueCookie", LevelScenario, StatusPlanned),
		baselineEntry("cookie", "QueuedFrom returns a queued Cookie", "查询已排队 Cookie", "Querying Queued Cookies", "demo:cookie queued", "queued", "TestCookieDemoQueued", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "HasQueuedFrom checks queued existence", "查询已排队 Cookie", "Querying Queued Cookies", "demo:cookie has-queued", "has-queued", "TestCookieDemoHasQueued", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "Scoped queued lookup distinguishes path and domain", "查询已排队 Cookie", "Querying Queued Cookies", "demo:cookie scoped-queued", "scoped-queued", "TestCookieDemoScopedQueued", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "UnqueueFrom removes an unwritten Cookie", "移除排队项", "Removing Queued Items", "demo:cookie unqueue", "unqueue", "TestCookieDemoUnqueue", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "QueueFrom accesses the middleware queue", "请求级 vs 进程级 API", "Request-Level vs Process-Level API", "demo:cookie queue-from", "queue-from", "TestCookieDemoQueueFrom", LevelScenario, StatusPlanned),
		baselineEntry("cookie", "Missing request queue returns ErrQueueNotFound", "请求级 vs 进程级 API", "Request-Level vs Process-Level API", "demo:cookie queue-not-found", "queue-not-found", "TestCookieDemoQueueNotFound", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "Process-level QueueMake, Queued, and Unqueue", "请求级 vs 进程级 API", "Request-Level vs Process-Level API", "demo:cookie process-queue", "process-queue", "TestCookieDemoProcessQueue", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "RequestCookie reads a request value", "基础读取", "Basic Retrieval", "demo:cookie request-cookie", "request-cookie", "TestCookieDemoRequestCookie", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "Missing request Cookie returns ErrCookieNotFound", "基础读取", "Basic Retrieval", "demo:cookie request-not-found", "request-not-found", "TestCookieDemoRequestNotFound", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "RequestWithContext propagates to security extensions", "带安全扩展读取", "Retrieval with Security Extensions", "demo:cookie request-context", "request-context", "TestCookieDemoRequestContext", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "RequestWithSigner verifies a signed Cookie", "带安全扩展读取", "Retrieval with Security Extensions", "demo:cookie request-signer", "request-signer", "TestCookieDemoRequestSigner", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "RequestWithEncryptor decrypts a Cookie", "带安全扩展读取", "Retrieval with Security Extensions", "demo:cookie request-encryptor", "request-encryptor", "TestCookieDemoRequestEncryptor", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "QueueExpireFrom expires a Cookie", "删除 Cookie", "Deleting Cookies", "demo:cookie queue-expire", "queue-expire", "TestCookieDemoQueueExpire", LevelScenario, StatusPlanned),
		baselineEntry("cookie", "QueueForgetFrom aliases request-level expiration", "删除 Cookie", "Deleting Cookies", "demo:cookie queue-forget", "queue-forget", "TestCookieDemoQueueForget", LevelScenario, StatusPlanned),
		baselineEntry("cookie", "Forget directly attaches an expired Cookie", "删除 Cookie", "Deleting Cookies", "demo:cookie forget", "forget", "TestCookieDemoForget", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "Deletion requires matching Path and Domain", "删除 Cookie", "Deleting Cookies", "demo:cookie deletion-scope", "deletion-scope", "TestCookieDemoDeletionScope", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "SameSite default and disabled output", "SameSite 策略", "SameSite Policy", "demo:cookie same-site-default", "same-site-default", "TestCookieDemoSameSiteDefault", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "SameSite Lax, Strict, and None output", "SameSite 策略", "SameSite Policy", "demo:cookie same-site-modes", "same-site-modes", "TestCookieDemoSameSiteModes", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "Signer and Encryptor contract methods", "安全契约接口", "Security Contract Interfaces", "demo:cookie security-contracts", "security-contracts", "TestCookieDemoSecurityContracts", LevelCompile, StatusPlanned),
		baselineEntry("cookie", "Encryption precedes signing on write", "写出与读取顺序", "Outgoing and Incoming Order", "demo:cookie outgoing-order", "outgoing-order", "TestCookieDemoOutgoingOrder", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "Verification precedes decryption on read", "写出与读取顺序", "Outgoing and Incoming Order", "demo:cookie incoming-order", "incoming-order", "TestCookieDemoIncomingOrder", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "PassthroughSecurity preserves values", "默认透传实现", "Default Passthrough Implementation", "demo:cookie passthrough", "passthrough", "TestCookieDemoPassthrough", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "WithSigner and WithEncryptor transform Attach values", "默认透传实现", "Default Passthrough Implementation", "demo:cookie attach-security", "attach-security", "TestCookieDemoAttachSecurity", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "NewQueue security options apply during Flush", "默认透传实现", "Default Passthrough Implementation", "demo:cookie queue-security", "queue-security", "TestCookieDemoQueueSecurity", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "SensitiveError redacts security inputs and preserves errors.Is", "错误脱敏", "Error Sanitization", "demo:cookie sensitive-error", "sensitive-error", "TestCookieDemoSensitiveError", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "Cookie error constants and failure categories", "错误常量", "Error Constants", "demo:cookie errors", "errors", "TestCookieDemoErrors", LevelHermetic, StatusPlanned),
		baselineEntry("cookie", "Laravel Cookie API equivalents", "与 Laravel Cookie 的对应关系", "Laravel Cookie Mapping", "demo:cookie laravel-compatibility", "laravel-compatibility", "TestCookieDemoLaravelCompatibility", LevelCompile, StatusPlanned),
	}
}
