package catalog

func eventEntries() []Entry {
	return []Entry{
		baselineEntry("event", "Event bus architecture", "简介", "Introduction", "demo:event architecture", "architecture", "TestEventDemoArchitecture", LevelCompile, StatusPlanned),
		baselineEntry("event", "Explicit listener registration", "手动注册监听器", "Manually Registering Listeners", "demo:event manual-registration", "manual-registration", "TestEventDemoManualRegistration", LevelCompile, StatusPlanned),
		baselineEntry("event", "Struct listener registration", "手动注册监听器", "Manually Registering Listeners", "demo:event struct-registration", "struct-registration", "TestEventDemoStructRegistration", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Closure listener registration", "闭包监听器", "Closure Listeners", "demo:event closure-listener", "closure-listener", "TestEventDemoClosureListener", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Prefix wildcard listeners", "通配符监听器", "Wildcard Event Listeners", "demo:event wildcard-prefix", "wildcard-prefix", "TestEventDemoPrefixWildcard", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Catch-all wildcard listeners", "通配符监听器", "Wildcard Event Listeners", "demo:event wildcard-all", "wildcard-all", "TestEventDemoCatchAllWildcard", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Exact-only Forget and Has semantics", "通配符监听器", "Wildcard Event Listeners", "demo:event wildcard-exact-operations", "wildcard-exact-operations", "TestEventDemoWildcardExactOperations", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Event definitions", "定义事件", "Defining Events", "demo:event event-definition", "event-definition", "TestEventDemoEventDefinition", LevelCompile, StatusPlanned),
		baselineEntry("event", "Event naming conventions", "定义事件", "Defining Events", "demo:event event-naming", "event-naming", "TestEventDemoEventNaming", LevelCompile, StatusPlanned),
		baselineEntry("event", "Serializable event payload boundaries", "定义事件", "Defining Events", "demo:event payload-boundaries", "payload-boundaries", "TestEventDemoPayloadBoundaries", LevelCompile, StatusPlanned),
		baselineEntry("event", "Struct listeners", "结构体监听器", "Struct Listeners", "demo:event struct-listener", "struct-listener", "TestEventDemoStructListener", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Function listeners", "函数式监听器", "Function Listeners", "demo:event listener-func", "listener-func", "TestEventDemoListenerFunc", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Non-stoppable event propagation", "停止事件传播", "Stopping The Propagation Of An Event", "demo:event propagation", "propagation", "TestEventDemoPropagation", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Queued listener prerequisites", "Queued Event Listeners", "Queued Event Listeners", "demo:event queue-prerequisites", "queue-prerequisites", "TestEventDemoQueuePrerequisites", LevelCompile, StatusPlanned),
		baselineEntry("event", "ShouldQueue listener dispatch", "实现 ShouldQueue 接口", "Implementing ShouldQueue", "demo:event should-queue", "should-queue", "TestEventDemoShouldQueue", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Queued listener wrapper", "使用 Queued 包装器", "Using the Queued Wrapper", "demo:event queued-wrapper", "queued-wrapper", "TestEventDemoQueuedWrapper", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Synchronous queued listener execution", "使用 Queued 包装器", "Using the Queued Wrapper", "demo:event queued-sync", "queued-sync", "TestEventDemoQueuedSync", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Redis worker queued listener execution", "使用 Queued 包装器", "Using the Queued Wrapper", "demo:event queued-redis --connection=redis", "queued-redis", "TestEventDemoQueuedRedis", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("event", "Queued listener connection, queue, and delay", "自定义队列连接、队列名与延迟", "Customizing the Queue Connection, Queue Name, & Delay", "demo:event queue-routing-options", "queue-routing-options", "TestEventDemoQueueRoutingOptions", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Queued listener retry, backoff, and timeout", "自定义队列连接、队列名与延迟", "Customizing the Queue Connection, Queue Name, & Delay", "demo:event queue-retry-options", "queue-retry-options", "TestEventDemoQueueRetryOptions", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Queued event factory registration", "注册事件工厂", "Registering Event Factories", "demo:event event-factory", "event-factory", "TestEventDemoEventFactory", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Queued event factory validation", "注册事件工厂", "Registering Event Factories", "demo:event event-factory-validation", "event-factory-validation", "TestEventDemoEventFactoryValidation", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Unregistered queued event fallback", "注册事件工厂", "Registering Event Factories", "demo:event raw-queued-event", "raw-queued-event", "TestEventDemoRawQueuedEvent", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Event dispatch", "派发事件", "Dispatching Events", "demo:event dispatch", "dispatch", "TestEventDemoDispatch", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Dispatch failure isolation", "派发事件", "Dispatching Events", "demo:event dispatch-isolation", "dispatch-isolation", "TestEventDemoDispatchIsolation", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Nil context and event dispatch", "派发事件", "Dispatching Events", "demo:event nil-dispatch", "nil-dispatch", "TestEventDemoNilDispatch", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Event subscriber implementation", "编写 Event Subscribers", "Writing Event Subscribers", "demo:event subscriber", "subscriber", "TestEventDemoSubscriber", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Event subscriber registration", "注册 Event Subscribers", "Registering Event Subscribers", "demo:event subscriber-registration", "subscriber-registration", "TestEventDemoSubscriberRegistration", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Package-level facade operations", "全局门面", "Global Facade", "demo:event facade", "facade", "TestEventDemoFacade", LevelScenario, StatusPlanned),
		baselineEntry("event", "Goroutine-based async listeners", "异步监听器", "Async Listeners", "demo:event async", "async", "TestEventDemoAsync", LevelScenario, StatusPlanned),
		baselineEntry("event", "Async listener durability boundaries", "异步监听器", "Async Listeners", "demo:event async-durability", "async-durability", "TestEventDemoAsyncDurability", LevelCompile, StatusPlanned),
		baselineEntry("event", "Application lifecycle events", "应用生命周期", "Application Lifecycle", "demo:event app-lifecycle", "app-lifecycle", "TestEventDemoApplicationLifecycle", LevelScenario, StatusPlanned),
		baselineEntry("event", "Provider lifecycle events", "Provider 生命周期", "Provider Lifecycle", "demo:event provider-lifecycle", "provider-lifecycle", "TestEventDemoProviderLifecycle", LevelScenario, StatusPlanned),
		baselineEntry("event", "HTTP server lifecycle events", "HTTP 服务生命周期", "HTTP Server Lifecycle", "demo:event server-lifecycle", "server-lifecycle", "TestEventDemoServerLifecycle", LevelScenario, StatusPlanned),
		baselineEntry("event", "HTTP request lifecycle events", "HTTP 请求生命周期", "HTTP Request Lifecycle", "demo:event request-lifecycle", "request-lifecycle", "TestEventDemoRequestLifecycle", LevelScenario, StatusPlanned),
		baselineEntry("event", "HTTP request finished ordering", "HTTP 请求生命周期", "HTTP Request Lifecycle", "demo:event request-finished-ordering", "request-finished-ordering", "TestEventDemoRequestFinishedOrdering", LevelScenario, StatusPlanned),
		baselineEntry("event", "Console lifecycle events", "Console 生命周期", "Console Lifecycle", "demo:event console-lifecycle", "console-lifecycle", "TestEventDemoConsoleLifecycle", LevelScenario, StatusPlanned),
		baselineEntry("event", "Vendor publish lifecycle event", "Vendor Publish 事件", "Vendor Publish Event", "demo:event vendor-publish-event", "vendor-publish-event", "TestEventDemoVendorPublishEvent", LevelScenario, StatusPlanned),
		baselineEntry("event", "Synchronous listener error isolation", "错误与 Panic 处理", "Error and Panic Handling", "demo:event listener-error-isolation", "listener-error-isolation", "TestEventDemoListenerErrorIsolation", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Synchronous listener panic isolation", "错误与 Panic 处理", "Error and Panic Handling", "demo:event listener-panic-isolation", "listener-panic-isolation", "TestEventDemoListenerPanicIsolation", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Async listener failure isolation", "错误与 Panic 处理", "Error and Panic Handling", "demo:event async-failure-isolation", "async-failure-isolation", "TestEventDemoAsyncFailureIsolation", LevelScenario, StatusPlanned),
		baselineEntry("event", "Queued listener failure handling", "错误与 Panic 处理", "Error and Panic Handling", "demo:event queued-failure-handling", "queued-failure-handling", "TestEventDemoQueuedFailureHandling", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Strong-consistency boundary", "错误与 Panic 处理", "Error and Panic Handling", "demo:event consistency-boundary", "consistency-boundary", "TestEventDemoConsistencyBoundary", LevelCompile, StatusPlanned),
		baselineEntry("event", "Isolated dispatcher testing", "测试", "Testing", "demo:event isolated-testing", "isolated-testing", "TestEventDemoIsolatedTesting", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Synchronous queue listener testing", "测试", "Testing", "demo:event queued-sync-testing", "queued-sync-testing", "TestEventDemoQueuedSyncTesting", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Real worker listener testing", "测试", "Testing", "demo:event queued-worker-testing --connection=redis", "queued-worker-testing", "TestEventDemoQueuedWorkerTesting", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("event", "Event interface contract", "Event", "Event", "demo:event event-interface", "event-interface", "TestEventDemoEventInterface", LevelCompile, StatusPlanned),
		baselineEntry("event", "Listener interface contract", "Listener", "Listener", "demo:event listener-interface", "listener-interface", "TestEventDemoListenerInterface", LevelCompile, StatusPlanned),
		baselineEntry("event", "ListenerFunc adapter contract", "ListenerFunc", "ListenerFunc", "demo:event listener-func-interface", "listener-func-interface", "TestEventDemoListenerFuncInterface", LevelCompile, StatusPlanned),
		baselineEntry("event", "Dispatcher interface contract", "Dispatcher", "Dispatcher", "demo:event dispatcher-interface", "dispatcher-interface", "TestEventDemoDispatcherInterface", LevelCompile, StatusPlanned),
		baselineEntry("event", "Subscriber interface contract", "Subscriber", "Subscriber", "demo:event subscriber-interface", "subscriber-interface", "TestEventDemoSubscriberInterface", LevelCompile, StatusPlanned),
		baselineEntry("event", "ShouldQueue interface contract", "ShouldQueue", "ShouldQueue", "demo:event should-queue-interface", "should-queue-interface", "TestEventDemoShouldQueueInterface", LevelCompile, StatusPlanned),
		baselineEntry("event", "AsyncListener interface contract", "AsyncListener", "AsyncListener", "demo:event async-listener-interface", "async-listener-interface", "TestEventDemoAsyncListenerInterface", LevelCompile, StatusPlanned),
		baselineEntry("event", "QueueOptionsProvider interface contract", "QueueOptionsProvider", "QueueOptionsProvider", "demo:event queue-options-interface", "queue-options-interface", "TestEventDemoQueueOptionsInterface", LevelCompile, StatusPlanned),
		baselineEntry("event", "Event ServiceProvider registration", "ServiceProvider", "ServiceProvider", "demo:event provider-register", "provider-register", "TestEventDemoProviderRegister", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Event ServiceProvider queue bootstrapping", "ServiceProvider", "ServiceProvider", "demo:event provider-boot", "provider-boot", "TestEventDemoProviderBoot", LevelHermetic, StatusPlanned),
		baselineEntry("event", "Laravel events compatibility matrix", "与 Laravel 13 的差异", "Laravel 13 Differences", "demo:event laravel-compatibility", "laravel-compatibility", "TestEventDemoLaravelCompatibility", LevelCompile, StatusPlanned),
	}
}
