package catalog

func filesystemEntries() []Entry {
	return []Entry{
		baselineEntry("filesystem", "Manager and repository architecture", "简介", "Introduction", "demo:filesystem architecture", "architecture", "TestFilesystemDemoArchitecture", LevelCompile, StatusPlanned),
		baselineEntry("filesystem", "Configuration loading", "配置文件", "Configuration File", "demo:filesystem config", "config", "TestFilesystemDemoConfiguration", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Local driver prerequisites", "驱动前置条件", "Driver Prerequisites", "demo:filesystem local-prerequisites", "local-prerequisites", "TestFilesystemDemoLocalPrerequisites", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "OSS driver prerequisites", "驱动前置条件", "Driver Prerequisites", "demo:filesystem oss-prerequisites --disk=oss", "oss-prerequisites", "TestFilesystemDemoOSSPrerequisites", LevelIntegration, StatusPlanned, "oss"),
		baselineEntry("filesystem", "Top-level configuration", "顶层配置", "Top-Level Configuration", "demo:filesystem top-level-config", "top-level-config", "TestFilesystemDemoTopLevelConfiguration", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Local disk configuration", "Local 磁盘", "Local Disk", "demo:filesystem local-config", "local-config", "TestFilesystemDemoLocalConfiguration", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Public disk configuration", "Public 磁盘", "Public Disk", "demo:filesystem public-config", "public-config", "TestFilesystemDemoPublicConfiguration", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "OSS disk configuration", "OSS 磁盘", "OSS Disk", "demo:filesystem oss-config --disk=oss", "oss-config", "TestFilesystemDemoOSSConfiguration", LevelIntegration, StatusPlanned, "oss"),
		baselineEntry("filesystem", "Symbolic link configuration", "符号链接配置", "Symbolic Link Configuration", "demo:filesystem links-config", "links-config", "TestFilesystemDemoLinksConfiguration", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Disk configuration fields", "磁盘配置字段说明", "Disk Configuration Fields", "demo:filesystem disk-config", "disk-config", "TestFilesystemDemoDiskConfiguration", LevelCompile, StatusPlanned),
		baselineEntry("filesystem", "Package-level facade", "包级 Facade", "Package-Level Facade", "demo:filesystem facade", "facade", "TestFilesystemDemoFacade", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Named disk operations", "指定磁盘", "Named Disks", "demo:filesystem named-disk", "named-disk", "TestFilesystemDemoNamedDisk", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Cloud disk selection", "云磁盘", "Cloud Disk", "demo:filesystem cloud", "cloud", "TestFilesystemDemoCloudDisk", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Interface selection guidance", "接口选择建议", "Interface Selection Guide", "demo:filesystem interface-selection", "interface-selection", "TestFilesystemDemoInterfaceSelection", LevelCompile, StatusPlanned),
		baselineEntry("filesystem", "Whole-file reads", "读取全部内容", "Reading File Contents", "demo:filesystem get", "get", "TestFilesystemDemoGet", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "JSON deserialization", "读取并反序列化 JSON", "Reading and Deserializing JSON", "demo:filesystem json", "json", "TestFilesystemDemoJSON", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Streaming reads with metadata", "流式读取", "Streaming Reads", "demo:filesystem open-stream", "open-stream", "TestFilesystemDemoOpenStream", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Streaming read alias", "流式读取", "Streaming Reads", "demo:filesystem read-stream", "read-stream", "TestFilesystemDemoReadStream", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Downloads to writers", "下载到 Writer", "Downloading to a Writer", "demo:filesystem download", "download", "TestFilesystemDemoDownload", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "File existence aliases", "判断文件存在", "Determining File Existence", "demo:filesystem file-existence", "file-existence", "TestFilesystemDemoFileExistence", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Directory existence", "判断目录存在", "Determining Directory Existence", "demo:filesystem directory-existence", "directory-existence", "TestFilesystemDemoDirectoryExistence", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "String byte and reader writes", "基础写入", "Basic Writes", "demo:filesystem put", "put", "TestFilesystemDemoPut", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Streaming write aliases", "流式写入", "Streaming Writes", "demo:filesystem put-reader", "put-reader", "TestFilesystemDemoPutReader", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Prepend and append semantics", "前置追加与末尾追加", "Prepending and Appending", "demo:filesystem prepend-append", "prepend-append", "TestFilesystemDemoPrependAppend", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Write visibility and content type options", "PutOptions 说明", "PutOptions Reference", "demo:filesystem put-options", "put-options", "TestFilesystemDemoPutOptions", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Uploads with original names", "PutFile", "PutFile", "demo:filesystem put-file", "put-file", "TestFilesystemDemoPutFile", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Uploads with specified names", "PutFileAs", "PutFileAs", "demo:filesystem put-file-as", "put-file-as", "TestFilesystemDemoPutFileAs", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Upload persistence fields", "推荐业务字段", "Recommended Database Fields", "demo:filesystem upload-fields", "upload-fields", "TestFilesystemDemoUploadFields", LevelCompile, StatusPlanned),
		baselineEntry("filesystem", "Copy and move operations", "复制与移动", "Copying and Moving", "demo:filesystem copy-move", "copy-move", "TestFilesystemDemoCopyMove", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Cross-disk operation guard", "复制与移动", "Copying and Moving", "demo:filesystem cross-disk-guard", "cross-disk-guard", "TestFilesystemDemoCrossDiskGuard", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Multi-file deletion", "删除文件", "Deleting Files", "demo:filesystem delete", "delete", "TestFilesystemDemoDelete", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "File size metadata", "文件元信息", "File Metadata", "demo:filesystem size", "size", "TestFilesystemDemoSize", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Last-modified metadata", "文件元信息", "File Metadata", "demo:filesystem last-modified", "last-modified", "TestFilesystemDemoLastModified", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Complete file metadata", "文件元信息", "File Metadata", "demo:filesystem file-info", "file-info", "TestFilesystemDemoFileInfo", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "MIME type detection", "文件元信息", "File Metadata", "demo:filesystem mime-type", "mime-type", "TestFilesystemDemoMimeType", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "SHA-256 checksums", "文件校验和", "File Checksums", "demo:filesystem checksum", "checksum", "TestFilesystemDemoChecksum", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Physical and logical paths", "物理路径", "Physical Paths", "demo:filesystem path", "path", "TestFilesystemDemoPath", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Directory creation", "目录操作", "Directories", "demo:filesystem make-directory", "make-directory", "TestFilesystemDemoMakeDirectory", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Shallow file listing", "目录操作", "Directories", "demo:filesystem files", "files", "TestFilesystemDemoFiles", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Recursive file listing", "目录操作", "Directories", "demo:filesystem all-files", "all-files", "TestFilesystemDemoAllFiles", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Shallow directory listing", "目录操作", "Directories", "demo:filesystem directories", "directories", "TestFilesystemDemoDirectories", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Recursive directory listing", "目录操作", "Directories", "demo:filesystem all-directories", "all-directories", "TestFilesystemDemoAllDirectories", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Safe directory deletion", "目录操作", "Directories", "demo:filesystem delete-directory", "delete-directory", "TestFilesystemDemoDeleteDirectory", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Public URL generation", "公开 URL", "Public URLs", "demo:filesystem public-url", "public-url", "TestFilesystemDemoPublicURL", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Public disk symbolic links", "公开磁盘符号链接", "Public Disk Symbolic Links", "demo:filesystem storage-link", "storage-link", "TestFilesystemDemoStorageLink", LevelScenario, StatusPlanned),
		baselineEntry("filesystem", "Relative and forced symbolic links", "公开磁盘符号链接", "Public Disk Symbolic Links", "demo:filesystem storage-link-options", "storage-link-options", "TestFilesystemDemoStorageLinkOptions", LevelScenario, StatusPlanned),
		baselineEntry("filesystem", "Safe symbolic link removal", "公开磁盘符号链接", "Public Disk Symbolic Links", "demo:filesystem storage-unlink", "storage-unlink", "TestFilesystemDemoStorageUnlink", LevelScenario, StatusPlanned),
		baselineEntry("filesystem", "Temporary signed URLs", "临时签名 URL", "Temporary Signed URLs", "demo:filesystem temporary-url", "temporary-url", "TestFilesystemDemoTemporaryURL", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Temporary URL capability detection", "临时签名 URL", "Temporary Signed URLs", "demo:filesystem temporary-url-capability", "temporary-url-capability", "TestFilesystemDemoTemporaryURLCapability", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "OSS temporary upload URLs", "临时上传 URL", "Temporary Upload URLs", "demo:filesystem temporary-upload-url --disk=oss", "temporary-upload-url", "TestFilesystemDemoTemporaryUploadURL", LevelIntegration, StatusPlanned, "oss"),
		baselineEntry("filesystem", "Temporary upload URL capability detection", "临时上传 URL", "Temporary Upload URLs", "demo:filesystem temporary-upload-capability", "temporary-upload-capability", "TestFilesystemDemoTemporaryUploadCapability", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Local signed URL verification", "校验本地签名 URL", "Verifying Local Signed URLs", "demo:filesystem verify-temporary-url", "verify-temporary-url", "TestFilesystemDemoVerifyTemporaryURL", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Local disk visibility semantics", "可见性", "Visibility", "demo:filesystem local-visibility", "local-visibility", "TestFilesystemDemoLocalVisibility", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "OSS object visibility ACLs", "可见性", "Visibility", "demo:filesystem oss-visibility --disk=oss", "oss-visibility", "TestFilesystemDemoOSSVisibility", LevelIntegration, StatusPlanned, "oss"),
		baselineEntry("filesystem", "OSS disk switching and ACL mapping", "OSS 驱动", "OSS Driver", "go test ./app/demo/filesystem -run TestFilesystemDemoOSSDriver", "oss-driver", "TestFilesystemDemoOSSDriver", LevelIntegration, StatusImplemented, "oss"),
		baselineEntry("filesystem", "Custom driver registration", "注册 Driver", "Registering a Driver", "demo:filesystem custom-driver", "custom-driver", "TestFilesystemDemoCustomDriver", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Custom driver replacement and lifecycle", "注册 Driver", "Registering a Driver", "demo:filesystem custom-driver-lifecycle", "custom-driver-lifecycle", "TestFilesystemDemoCustomDriverLifecycle", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Driver contract", "Driver 接口", "Driver Interface", "demo:filesystem driver-contract", "driver-contract", "TestFilesystemDemoDriverContract", LevelCompile, StatusPlanned),
		baselineEntry("filesystem", "Optional driver capabilities and fallbacks", "Driver 接口", "Driver Interface", "demo:filesystem optional-driver-capabilities", "optional-driver-capabilities", "TestFilesystemDemoOptionalDriverCapabilities", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Driver factory context", "DriverFactoryContext 字段说明", "DriverFactoryContext Fields", "demo:filesystem driver-factory-context", "driver-factory-context", "TestFilesystemDemoDriverFactoryContext", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Manual manager construction and cleanup", "手动初始化", "Manual Initialization", "demo:filesystem manual-manager", "manual-manager", "TestFilesystemDemoManualManager", LevelScenario, StatusPlanned),
		baselineEntry("filesystem", "Manager construction from application config", "手动初始化", "Manual Initialization", "demo:filesystem manager-from-config", "manager-from-config", "TestFilesystemDemoManagerFromConfig", LevelScenario, StatusPlanned),
		baselineEntry("filesystem", "Filesystem error constants", "错误常量", "Error Constants", "demo:filesystem errors", "errors", "TestFilesystemDemoErrors", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "Local driver capability matrix", "驱动能力矩阵", "Driver Capability Matrix", "demo:filesystem local-capabilities", "local-capabilities", "TestFilesystemDemoLocalCapabilities", LevelHermetic, StatusPlanned),
		baselineEntry("filesystem", "OSS driver capability matrix", "驱动能力矩阵", "Driver Capability Matrix", "demo:filesystem oss-capabilities --disk=oss", "oss-capabilities", "TestFilesystemDemoOSSCapabilities", LevelIntegration, StatusPlanned, "oss"),
		baselineEntry("filesystem", "Laravel filesystem API mapping", "与 Laravel Filesystem 的对应关系", "Laravel Filesystem Mapping", "demo:filesystem laravel-compatibility", "laravel-compatibility", "TestFilesystemDemoLaravelCompatibility", LevelCompile, StatusPlanned),
		baselineEntry("filesystem", "Filesystem usage guidance", "使用建议", "Best Practices", "demo:filesystem best-practices", "best-practices", "TestFilesystemDemoBestPractices", LevelCompile, StatusPlanned),
	}
}
