package catalog

func httpServerEntries() []Entry {
	return []Entry{
		baselineEntry("http-server", "Application bootstrap constructs the HTTP server", "简介", "Introduction", "demo:http-server bootstrap", "bootstrap", "TestHTTPServerDemoBootstrap", LevelScenario, StatusPlanned),
		baselineEntry("http-server", "Register application routes through WithRouting", "简介", "Introduction", "demo:http-server routes", "routes", "TestHTTPServerDemoRoutes", LevelScenario, StatusPlanned),
		baselineEntry("http-server", "Start the HTTP server with serve", "启动服务", "Starting the Server", "demo:http-server serve", "serve", "TestHTTPServerDemoServe", LevelScenario, StatusPlanned),
		baselineEntry("http-server", "Override the listen port with --port", "启动服务", "Starting the Server", "demo:http-server port-flag", "port-flag", "TestHTTPServerDemoPortFlag", LevelScenario, StatusPlanned),
		baselineEntry("http-server", "Port flag does not persist configuration changes", "启动服务", "Starting the Server", "demo:http-server port-flag-scope", "port-flag-scope", "TestHTTPServerDemoPortFlagScope", LevelHermetic, StatusPlanned),
		baselineEntry("http-server", "app.server.host and SERVER_HOST", "监听地址", "Listen Address", "demo:http-server host", "host", "TestHTTPServerDemoHost", LevelHermetic, StatusPlanned),
		baselineEntry("http-server", "app.server.port and SERVER_PORT", "监听地址", "Listen Address", "demo:http-server port", "port", "TestHTTPServerDemoPort", LevelHermetic, StatusPlanned),
		baselineEntry("http-server", "app.server.timeout and SERVER_TIMEOUT", "超时与请求限制", "Timeouts and Request Limits", "demo:http-server timeout-fallback", "timeout-fallback", "TestHTTPServerDemoTimeoutFallback", LevelHermetic, StatusPlanned),
		baselineEntry("http-server", "app.server.read_timeout and SERVER_READ_TIMEOUT", "超时与请求限制", "Timeouts and Request Limits", "demo:http-server read-timeout", "read-timeout", "TestHTTPServerDemoReadTimeout", LevelHermetic, StatusPlanned),
		baselineEntry("http-server", "app.server.read_header_timeout and SERVER_READ_HEADER_TIMEOUT", "超时与请求限制", "Timeouts and Request Limits", "demo:http-server read-header-timeout", "read-header-timeout", "TestHTTPServerDemoReadHeaderTimeout", LevelHermetic, StatusPlanned),
		baselineEntry("http-server", "app.server.write_timeout and SERVER_WRITE_TIMEOUT", "超时与请求限制", "Timeouts and Request Limits", "demo:http-server write-timeout", "write-timeout", "TestHTTPServerDemoWriteTimeout", LevelHermetic, StatusPlanned),
		baselineEntry("http-server", "app.server.idle_timeout and SERVER_IDLE_TIMEOUT", "超时与请求限制", "Timeouts and Request Limits", "demo:http-server idle-timeout", "idle-timeout", "TestHTTPServerDemoIdleTimeout", LevelHermetic, StatusPlanned),
		baselineEntry("http-server", "app.server.shutdown_timeout and SERVER_SHUTDOWN_TIMEOUT", "超时与请求限制", "Timeouts and Request Limits", "demo:http-server shutdown-timeout", "shutdown-timeout", "TestHTTPServerDemoShutdownTimeout", LevelScenario, StatusPlanned),
		baselineEntry("http-server", "app.server.max_header_bytes and SERVER_MAX_HEADER_BYTES", "超时与请求限制", "Timeouts and Request Limits", "demo:http-server max-header-bytes", "max-header-bytes", "TestHTTPServerDemoMaxHeaderBytes", LevelScenario, StatusPlanned),
		baselineEntry("http-server", "app.server.max_multipart_memory and SERVER_MAX_MULTIPART_MEMORY", "超时与请求限制", "Timeouts and Request Limits", "demo:http-server max-multipart-memory", "max-multipart-memory", "TestHTTPServerDemoMaxMultipartMemory", LevelScenario, StatusPlanned),
		baselineEntry("http-server", "Parse Go duration strings for server timeouts", "超时与请求限制", "Timeouts and Request Limits", "demo:http-server duration-string", "duration-string", "TestHTTPServerDemoDurationString", LevelHermetic, StatusPlanned),
		baselineEntry("http-server", "Parse plain numeric timeout values as seconds", "超时与请求限制", "Timeouts and Request Limits", "demo:http-server duration-seconds", "duration-seconds", "TestHTTPServerDemoDurationSeconds", LevelHermetic, StatusPlanned),
		baselineEntry("http-server", "app.server.trusted_proxies and SERVER_TRUSTED_PROXIES", "代理与客户端 IP", "Proxies and Client IPs", "demo:http-server trusted-proxies", "trusted-proxies", "TestHTTPServerDemoTrustedProxies", LevelScenario, StatusPlanned),
		baselineEntry("http-server", "app.server.client_ip_headers and SERVER_CLIENT_IP_HEADERS", "代理与客户端 IP", "Proxies and Client IPs", "demo:http-server client-ip-headers", "client-ip-headers", "TestHTTPServerDemoClientIPHeaders", LevelScenario, StatusPlanned),
		baselineEntry("http-server", "Untrusted proxy headers cannot spoof the client IP", "代理与客户端 IP", "Proxies and Client IPs", "demo:http-server untrusted-client-ip", "untrusted-client-ip", "TestHTTPServerDemoUntrustedClientIP", LevelScenario, StatusPlanned),
		baselineEntry("http-server", "app.server.access_log and SERVER_ACCESS_LOG", "中间件开关", "Middleware Toggles", "demo:http-server access-log", "access-log", "TestHTTPServerDemoAccessLog", LevelScenario, StatusPlanned),
		baselineEntry("http-server", "app.server.exception_handler and SERVER_EXCEPTION_HANDLER", "中间件开关", "Middleware Toggles", "demo:http-server exception-handler", "exception-handler", "TestHTTPServerDemoExceptionHandler", LevelScenario, StatusPlanned),
		baselineEntry("http-server", "app.debug and APP_DEBUG control exception details", "中间件开关", "Middleware Toggles", "demo:http-server debug-exception", "debug-exception", "TestHTTPServerDemoDebugException", LevelScenario, StatusPlanned),
		baselineEntry("http-server", "Serve maintains a port-specific PID file", "进程控制", "Process Control", "demo:http-server pid-file", "pid-file", "TestHTTPServerDemoPIDFile", LevelScenario, StatusPlanned),
		baselineEntry("http-server", "Gracefully stop with --stop", "进程控制", "Process Control", "demo:http-server stop", "stop", "TestHTTPServerDemoStop", LevelScenario, StatusPlanned),
		baselineEntry("http-server", "Force stop with --kill", "进程控制", "Process Control", "demo:http-server kill", "kill", "TestHTTPServerDemoKill", LevelScenario, StatusPlanned),
		baselineEntry("http-server", "Reload by starting a replacement before stopping the old process", "进程控制", "Process Control", "demo:http-server reload", "reload", "TestHTTPServerDemoReload", LevelScenario, StatusPlanned),
		baselineEntry("http-server", "Restart by killing the old process before starting a replacement", "进程控制", "Process Control", "demo:http-server restart", "restart", "TestHTTPServerDemoRestart", LevelScenario, StatusPlanned),
		baselineEntry("http-server", "Report a missing PID file for process control", "进程控制", "Process Control", "demo:http-server missing-pid", "missing-pid", "TestHTTPServerDemoMissingPID", LevelScenario, StatusPlanned),
	}
}
