package catalog

func loggerEntries() []Entry {
	return []Entry{
		baselineEntry("logger", "Channel-based logging architecture", "简介", "Introduction", "demo:logger architecture", "architecture", "TestLoggerDemoArchitecture", LevelCompile, StatusPlanned),
		baselineEntry("logger", "Configuration loading and environment overrides", "配置文件", "Config File", "demo:logger config", "config", "TestLoggerDemoConfiguration", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Single file driver and directory creation", "Single 和 Daily 通道", "Single and Daily Channels", "demo:logger single-driver", "single-driver", "TestLoggerDemoSingleDriver", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Daily file rotation and dated filenames", "Single 和 Daily 通道", "Single and Daily Channels", "demo:logger daily-driver", "daily-driver", "TestLoggerDemoDailyDriver", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Standard error driver", "Stderr 通道", "Stderr Channel", "demo:logger stderr-driver", "stderr-driver", "TestLoggerDemoStderrDriver", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Null driver output suppression", "Null 通道", "Null Channel", "demo:logger null-driver", "null-driver", "TestLoggerDemoNullDriver", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Default channel configuration", "顶层配置", "Top-Level Configuration", "demo:logger top-level-config", "top-level-config", "TestLoggerDemoTopLevelConfiguration", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Channel driver, formatter, level, path, and stack options", "通道配置", "Channel Configuration", "demo:logger channel-config", "channel-config", "TestLoggerDemoChannelConfiguration", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Environment-specific logging configuration", "部署建议", "Deployment Recommendations", "demo:logger deployment-config", "deployment-config", "TestLoggerDemoDeploymentConfiguration", LevelCompile, StatusPlanned),
		baselineEntry("logger", "Stack channel fan-out", "构建日志堆栈", "Building Log Stacks", "demo:logger stack", "stack", "TestLoggerDemoStack", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Stack child level and formatter isolation", "构建日志堆栈", "Building Log Stacks", "demo:logger stack-channel-isolation", "stack-channel-isolation", "TestLoggerDemoStackChannelIsolation", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Log level thresholds", "日志级别", "Log Levels", "demo:logger levels", "levels", "TestLoggerDemoLevels", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Package-level logging facade", "使用 Facade", "Using the Facade", "demo:logger facade", "facade", "TestLoggerDemoFacade", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Formatted facade methods", "使用 Facade", "Using the Facade", "demo:logger formatted-facade", "formatted-facade", "TestLoggerDemoFormattedFacade", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Fatal logging process exit", "使用 Facade", "Using the Facade", "demo:logger fatal", "fatal", "TestLoggerDemoFatal", LevelScenario, StatusPlanned),
		baselineEntry("logger", "Single structured context field", "单个字段", "Single Field", "demo:logger with-field", "with-field", "TestLoggerDemoWithField", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Multiple structured context fields", "多个字段", "Multiple Fields", "demo:logger with-fields", "with-fields", "TestLoggerDemoWithFields", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Error context attachment", "错误上下文", "Error Context", "demo:logger with-error", "with-error", "TestLoggerDemoWithError", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Error stacktrace line formatting", "错误上下文", "Error Context", "demo:logger error-stacktrace", "error-stacktrace", "TestLoggerDemoErrorStacktrace", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Manager and channel context extraction", "Context 字段提取", "Context Extraction", "demo:logger context-extractor", "context-extractor", "TestLoggerDemoContextExtractor", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Context extraction without an extractor", "Context 字段提取", "Context Extraction", "demo:logger context-noop", "context-noop", "TestLoggerDemoContextNoop", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Named channel logging", "写入特定通道", "Writing to Specific Channels", "demo:logger named-channel", "named-channel", "TestLoggerDemoNamedChannel", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Missing named channel fallback", "写入特定通道", "Writing to Specific Channels", "demo:logger missing-channel", "missing-channel", "TestLoggerDemoMissingChannel", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Named channel context chaining", "写入特定通道", "Writing to Specific Channels", "demo:logger channel-context", "channel-context", "TestLoggerDemoChannelContext", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Facade Manager resolution", "接口参考", "Interface Reference", "demo:logger resolve-manager", "resolve-manager", "TestLoggerDemoResolveManager", LevelScenario, StatusPlanned),
		baselineEntry("logger", "Default channel name lookup", "接口参考", "Interface Reference", "demo:logger default-name", "default-name", "TestLoggerDemoDefaultName", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Driver interface contract", "自定义 Driver", "Custom Drivers", "demo:logger driver-contract", "driver-contract", "TestLoggerDemoDriverContract", LevelCompile, StatusPlanned),
		baselineEntry("logger", "Custom driver registration", "自定义 Driver", "Custom Drivers", "demo:logger custom-driver", "custom-driver", "TestLoggerDemoCustomDriver", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Custom driver replacement", "自定义 Driver", "Custom Drivers", "demo:logger custom-driver-replacement", "custom-driver-replacement", "TestLoggerDemoCustomDriverReplacement", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Custom formatter registration", "自定义 Formatter", "Custom Formatters", "demo:logger custom-formatter", "custom-formatter", "TestLoggerDemoCustomFormatter", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Formatter channel and custom parameters", "自定义 Formatter", "Custom Formatters", "demo:logger formatter-params", "formatter-params", "TestLoggerDemoFormatterParams", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Laravel-style line formatter", "内置 Formatter", "Built-in Formatters", "demo:logger line-formatter", "line-formatter", "TestLoggerDemoLineFormatter", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "logrus text formatter", "内置 Formatter", "Built-in Formatters", "demo:logger text-formatter", "text-formatter", "TestLoggerDemoTextFormatter", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "JSON line formatter", "内置 Formatter", "Built-in Formatters", "demo:logger json-formatter", "json-formatter", "TestLoggerDemoJSONFormatter", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Programmatic Manager initialization", "程序化初始化", "Programmatic Initialization", "demo:logger manual-manager", "manual-manager", "TestLoggerDemoManualManager", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Service Provider singleton and lazy initialization", "Service Provider", "Service Provider", "demo:logger provider-lifecycle", "provider-lifecycle", "TestLoggerDemoProviderLifecycle", LevelScenario, StatusPlanned),
		baselineEntry("logger", "Service Provider automatic cleanup", "Service Provider", "Service Provider", "demo:logger provider-cleanup", "provider-cleanup", "TestLoggerDemoProviderCleanup", LevelScenario, StatusPlanned),
		baselineEntry("logger", "Manager driver resource cleanup", "资源清理", "Resource Cleanup", "demo:logger resource-cleanup", "resource-cleanup", "TestLoggerDemoResourceCleanup", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Writes after Manager close", "资源清理", "Resource Cleanup", "demo:logger closed-writes", "closed-writes", "TestLoggerDemoClosedWrites", LevelHermetic, StatusPlanned),
		baselineEntry("logger", "Global logrus compatibility bridge", "与全局 logrus 的关系", "Relationship with Global logrus", "demo:logger global-logrus", "global-logrus", "TestLoggerDemoGlobalLogrus", LevelScenario, StatusPlanned),
	}
}
