package catalog

func loggerEntries() []Entry {
	return []Entry{
		baselineEntry("logger", "Channel-based logging architecture", "简介", "Introduction", "demo:logger architecture", "architecture", "TestLoggerDemoCases/architecture", LevelCompile, StatusImplemented),
		baselineEntry("logger", "Configuration loading and environment overrides", "配置文件", "Config File", "demo:logger config", "config", "TestLoggerDemoCases/config", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Single file driver and directory creation", "Single 和 Daily 通道", "Single and Daily Channels", "demo:logger single-driver", "single-driver", "TestLoggerDemoCases/single-driver", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Daily file rotation and dated filenames", "Single 和 Daily 通道", "Single and Daily Channels", "demo:logger daily-driver", "daily-driver", "TestLoggerDemoCases/daily-driver", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Standard error driver", "Stderr 通道", "Stderr Channel", "demo:logger stderr-driver", "stderr-driver", "TestLoggerDemoCases/stderr-driver", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Null driver output suppression", "Null 通道", "Null Channel", "demo:logger null-driver", "null-driver", "TestLoggerDemoCases/null-driver", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Default channel configuration", "顶层配置", "Top-Level Configuration", "demo:logger top-level-config", "top-level-config", "TestLoggerDemoCases/top-level-config", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Channel driver, formatter, level, path, and stack options", "通道配置", "Channel Configuration", "demo:logger channel-config", "channel-config", "TestLoggerDemoCases/channel-config", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Environment-specific logging configuration", "部署建议", "Deployment Recommendations", "demo:logger deployment-config", "deployment-config", "TestLoggerDemoCases/deployment-config", LevelCompile, StatusImplemented),
		baselineEntry("logger", "Stack channel fan-out", "构建日志堆栈", "Building Log Stacks", "demo:logger stack", "stack", "TestLoggerDemoCases/stack", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Stack child level and formatter isolation", "构建日志堆栈", "Building Log Stacks", "demo:logger stack-channel-isolation", "stack-channel-isolation", "TestLoggerDemoCases/stack-channel-isolation", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Log level thresholds", "日志级别", "Log Levels", "demo:logger levels", "levels", "TestLoggerDemoCases/levels", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Package-level logging facade", "使用 Facade", "Using the Facade", "demo:logger facade", "facade", "TestLoggerDemoCases/facade", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Formatted facade methods", "使用 Facade", "Using the Facade", "demo:logger formatted-facade", "formatted-facade", "TestLoggerDemoCases/formatted-facade", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Fatal logging process exit", "使用 Facade", "Using the Facade", "demo:logger fatal", "fatal", "TestLoggerDemoCases/fatal", LevelScenario, StatusImplemented),
		baselineEntry("logger", "Single structured context field", "单个字段", "Single Field", "demo:logger with-field", "with-field", "TestLoggerDemoCases/with-field", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Multiple structured context fields", "多个字段", "Multiple Fields", "demo:logger with-fields", "with-fields", "TestLoggerDemoCases/with-fields", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Error context attachment", "错误上下文", "Error Context", "demo:logger with-error", "with-error", "TestLoggerDemoCases/with-error", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Error stacktrace line formatting", "错误上下文", "Error Context", "demo:logger error-stacktrace", "error-stacktrace", "TestLoggerDemoCases/error-stacktrace", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Manager and channel context extraction", "Context 字段提取", "Context Extraction", "demo:logger context-extractor", "context-extractor", "TestLoggerDemoCases/context-extractor", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Context extraction without an extractor", "Context 字段提取", "Context Extraction", "demo:logger context-noop", "context-noop", "TestLoggerDemoCases/context-noop", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Named channel logging", "写入特定通道", "Writing to Specific Channels", "demo:logger named-channel", "named-channel", "TestLoggerDemoCases/named-channel", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Missing named channel fallback", "写入特定通道", "Writing to Specific Channels", "demo:logger missing-channel", "missing-channel", "TestLoggerDemoCases/missing-channel", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Named channel context chaining", "写入特定通道", "Writing to Specific Channels", "demo:logger channel-context", "channel-context", "TestLoggerDemoCases/channel-context", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Facade Manager resolution", "接口参考", "Interface Reference", "demo:logger resolve-manager", "resolve-manager", "TestLoggerDemoCases/resolve-manager", LevelScenario, StatusImplemented),
		baselineEntry("logger", "Default channel name lookup", "接口参考", "Interface Reference", "demo:logger default-name", "default-name", "TestLoggerDemoCases/default-name", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Driver interface contract", "自定义 Driver", "Custom Drivers", "demo:logger driver-contract", "driver-contract", "TestLoggerDemoCases/driver-contract", LevelCompile, StatusImplemented),
		baselineEntry("logger", "Custom driver registration", "自定义 Driver", "Custom Drivers", "demo:logger custom-driver", "custom-driver", "TestLoggerDemoCases/custom-driver", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Custom driver replacement", "自定义 Driver", "Custom Drivers", "demo:logger custom-driver-replacement", "custom-driver-replacement", "TestLoggerDemoCases/custom-driver-replacement", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Custom formatter registration", "自定义 Formatter", "Custom Formatters", "demo:logger custom-formatter", "custom-formatter", "TestLoggerDemoCases/custom-formatter", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Formatter channel and custom parameters", "自定义 Formatter", "Custom Formatters", "demo:logger formatter-params", "formatter-params", "TestLoggerDemoCases/formatter-params", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Laravel-style line formatter", "内置 Formatter", "Built-in Formatters", "demo:logger line-formatter", "line-formatter", "TestLoggerDemoCases/line-formatter", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "logrus text formatter", "内置 Formatter", "Built-in Formatters", "demo:logger text-formatter", "text-formatter", "TestLoggerDemoCases/text-formatter", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "JSON line formatter", "内置 Formatter", "Built-in Formatters", "demo:logger json-formatter", "json-formatter", "TestLoggerDemoCases/json-formatter", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Programmatic Manager initialization", "程序化初始化", "Programmatic Initialization", "demo:logger manual-manager", "manual-manager", "TestLoggerDemoCases/manual-manager", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Service Provider singleton and lazy initialization", "Service Provider", "Service Provider", "demo:logger provider-lifecycle", "provider-lifecycle", "TestLoggerDemoCases/provider-lifecycle", LevelScenario, StatusImplemented),
		baselineEntry("logger", "Service Provider automatic cleanup", "Service Provider", "Service Provider", "demo:logger provider-cleanup", "provider-cleanup", "TestLoggerDemoCases/provider-cleanup", LevelScenario, StatusImplemented),
		baselineEntry("logger", "Manager driver resource cleanup", "资源清理", "Resource Cleanup", "demo:logger resource-cleanup", "resource-cleanup", "TestLoggerDemoCases/resource-cleanup", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Writes after Manager close", "资源清理", "Resource Cleanup", "demo:logger closed-writes", "closed-writes", "TestLoggerDemoCases/closed-writes", LevelHermetic, StatusImplemented),
		baselineEntry("logger", "Global logrus compatibility bridge", "与全局 logrus 的关系", "Relationship with Global logrus", "demo:logger global-logrus", "global-logrus", "TestLoggerDemoCases/global-logrus", LevelScenario, StatusImplemented),
	}
}
