package catalog

func ratelimitEntries() []Entry {
	return []Entry{
		baselineEntry("ratelimit", "Rate limiter architecture", "架构概览", "Architecture", "demo:ratelimit architecture", "architecture", "TestRateLimitDemoArchitecture", LevelCompile, StatusPlanned),
		baselineEntry("ratelimit", "Limiter cache configuration", "配置项说明", "Configuration Items", "demo:ratelimit config", "config", "TestRateLimitDemoConfiguration", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Dedicated store and default-store fallback", "配置行为", "Configuration Items", "demo:ratelimit store-resolution", "store-resolution", "TestRateLimitDemoStoreResolution", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Single-process memory limiter state", "配置行为", "Configuration Items", "demo:ratelimit memory-store", "memory-store", "TestRateLimitDemoMemoryStore", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Shared Redis limiter state", "配置行为", "Configuration Items", "demo:ratelimit redis-store --store=redis", "redis-store", "TestRateLimitDemoRedisStore", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("ratelimit", "Cache configuration registration", "配置注册", "Configuration", "demo:ratelimit config-registration", "config-registration", "TestRateLimitDemoConfigurationRegistration", LevelCompile, StatusPlanned),
		baselineEntry("ratelimit", "Application startup initialization", "应用启动时自动初始化", "Quick Start", "demo:ratelimit auto-initialization", "auto-initialization", "TestRateLimitDemoAutomaticInitialization", LevelScenario, StatusPlanned),
		baselineEntry("ratelimit", "Named limiter route quick start", "注册命名限流器并挂载到路由", "Quick Start", "demo:ratelimit quick-start", "quick-start", "TestRateLimitDemoQuickStart", LevelScenario, StatusPlanned),
		baselineEntry("ratelimit", "Explicit standalone limiter construction", "独立程序或测试中显式创建", "Quick Start", "demo:ratelimit explicit-limiter", "explicit-limiter", "TestRateLimitDemoExplicitLimiter", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Named limiter registration", "注册命名限流器", "Named Limiters", "demo:ratelimit named-registration", "named-registration", "TestRateLimitDemoNamedRegistration", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Named limiter lookup", "读取已注册的命名限流器", "Named Limiters", "demo:ratelimit named-lookup", "named-lookup", "TestRateLimitDemoNamedLookup", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Unregistered limiter pass-through", "读取已注册的命名限流器", "Named Limiters", "demo:ratelimit unregistered-pass-through", "unregistered-pass-through", "TestRateLimitDemoUnregisteredPassThrough", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Independent counters for multiple rules", "多条规则同时生效", "Named Limiters", "demo:ratelimit multi-rule-counters", "multi-rule-counters", "TestRateLimitDemoMultipleRuleCounters", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Any over-limit rule blocks a request", "多条规则同时生效", "Named Limiters", "demo:ratelimit multi-rule-block", "multi-rule-block", "TestRateLimitDemoMultipleRuleBlock", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Limit value contract", "Limit 结构体", "Limit Builders", "demo:ratelimit limit-contract", "limit-contract", "TestRateLimitDemoLimitContract", LevelCompile, StatusPlanned),
		baselineEntry("ratelimit", "Custom fixed-window builder", "构造器列表", "Limit Builders", "demo:ratelimit every", "every", "TestRateLimitDemoEvery", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Per-second limit builder", "构造器列表", "Limit Builders", "demo:ratelimit per-second", "per-second", "TestRateLimitDemoPerSecond", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Per-minute limit builder", "构造器列表", "Limit Builders", "demo:ratelimit per-minute", "per-minute", "TestRateLimitDemoPerMinute", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Multi-minute limit builder", "构造器列表", "Limit Builders", "demo:ratelimit per-minutes", "per-minutes", "TestRateLimitDemoPerMinutes", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Per-hour limit builder", "构造器列表", "Limit Builders", "demo:ratelimit per-hour", "per-hour", "TestRateLimitDemoPerHour", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Per-day limit builder", "构造器列表", "Limit Builders", "demo:ratelimit per-day", "per-day", "TestRateLimitDemoPerDay", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Disabled limit builder", "构造器列表", "Limit Builders", "demo:ratelimit none", "none", "TestRateLimitDemoNone", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Dimension key isolation", "By", "By", "demo:ratelimit by", "by", "TestRateLimitDemoBy", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Duplicate-key fallback", "FallbackKey", "FallbackKey", "demo:ratelimit fallback-key", "fallback-key", "TestRateLimitDemoFallbackKey", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "After callback counts matching responses", "After", "After", "demo:ratelimit after-count", "after-count", "TestRateLimitDemoAfterCount", LevelScenario, StatusPlanned),
		baselineEntry("ratelimit", "After callback skips non-matching responses", "After", "After", "demo:ratelimit after-skip", "after-skip", "TestRateLimitDemoAfterSkip", LevelScenario, StatusPlanned),
		baselineEntry("ratelimit", "After rules expose pre-count response headers", "After", "After", "demo:ratelimit after-headers", "after-headers", "TestRateLimitDemoAfterHeaders", LevelScenario, StatusPlanned),
		baselineEntry("ratelimit", "Custom over-limit response", "Response", "Response", "demo:ratelimit custom-response", "custom-response", "TestRateLimitDemoCustomResponse", LevelScenario, StatusPlanned),
		baselineEntry("ratelimit", "Runtime result contract", "Result 结构体", "Result", "demo:ratelimit result-contract", "result-contract", "TestRateLimitDemoResultContract", LevelCompile, StatusPlanned),
		baselineEntry("ratelimit", "Global limiter middleware", "使用全局限流器", "Gin Middleware", "demo:ratelimit throttle", "throttle", "TestRateLimitDemoThrottle", LevelScenario, StatusPlanned),
		baselineEntry("ratelimit", "Explicit limiter middleware", "使用显式限流器实例", "Gin Middleware", "demo:ratelimit throttle-for", "throttle-for", "TestRateLimitDemoThrottleFor", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Disabled middleware rules pass through", "中间件行为", "Gin Middleware", "demo:ratelimit disabled-rule", "disabled-rule", "TestRateLimitDemoDisabledRule", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Default over-limit response", "默认响应", "Gin Middleware", "demo:ratelimit default-response", "default-response", "TestRateLimitDemoDefaultResponse", LevelScenario, StatusPlanned),
		baselineEntry("ratelimit", "Successful request rate-limit headers", "响应头", "Gin Middleware", "demo:ratelimit success-headers", "success-headers", "TestRateLimitDemoSuccessHeaders", LevelScenario, StatusPlanned),
		baselineEntry("ratelimit", "Over-limit response headers", "响应头", "Gin Middleware", "demo:ratelimit over-limit-headers", "over-limit-headers", "TestRateLimitDemoOverLimitHeaders", LevelScenario, StatusPlanned),
		baselineEntry("ratelimit", "Tightest-rule success headers", "响应头", "Gin Middleware", "demo:ratelimit tightest-headers", "tightest-headers", "TestRateLimitDemoTightestHeaders", LevelScenario, StatusPlanned),
		baselineEntry("ratelimit", "Route-group middleware mounting", "分组挂载", "Gin Middleware", "demo:ratelimit route-group", "route-group", "TestRateLimitDemoRouteGroup", LevelScenario, StatusPlanned),
		baselineEntry("ratelimit", "Legacy route package compatibility", "route 包兼容用法", "Compatibility Through the route Package", "demo:ratelimit route-compatibility", "route-compatibility", "TestRateLimitDemoRouteCompatibility", LevelScenario, StatusPlanned),
		baselineEntry("ratelimit", "Package-level facade operations", "包级 facade", "Manual Counting API", "demo:ratelimit facade", "facade", "TestRateLimitDemoFacade", LevelScenario, StatusPlanned),
		baselineEntry("ratelimit", "Explicit limiter instance operations", "包级 facade", "Manual Counting API", "demo:ratelimit instance", "instance", "TestRateLimitDemoInstance", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Record one attempt", "Hit", "Hit", "demo:ratelimit hit", "hit", "TestRateLimitDemoHit", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Default decay for non-positive windows", "Hit", "Hit", "demo:ratelimit hit-default-decay", "hit-default-decay", "TestRateLimitDemoHitDefaultDecay", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Increment by a custom amount", "Increment", "Increment / Decrement", "demo:ratelimit increment", "increment", "TestRateLimitDemoIncrement", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Default increment amount", "Increment", "Increment / Decrement", "demo:ratelimit increment-default", "increment-default", "TestRateLimitDemoIncrementDefault", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Decrement by a custom amount", "Decrement", "Increment / Decrement", "demo:ratelimit decrement", "decrement", "TestRateLimitDemoDecrement", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Default decrement amount", "Decrement", "Increment / Decrement", "demo:ratelimit decrement-default", "decrement-default", "TestRateLimitDemoDecrementDefault", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Read current attempts", "Attempts", "Attempts", "demo:ratelimit attempts", "attempts", "TestRateLimitDemoAttempts", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Missing attempt counter", "Attempts", "Attempts", "demo:ratelimit attempts-missing", "attempts-missing", "TestRateLimitDemoMissingAttempts", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Detect exhausted attempt limit", "TooManyAttempts", "TooManyAttempts", "demo:ratelimit too-many-attempts", "too-many-attempts", "TestRateLimitDemoTooManyAttempts", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Disabled non-positive attempt limit", "TooManyAttempts", "TooManyAttempts", "demo:ratelimit non-positive-limit", "non-positive-limit", "TestRateLimitDemoNonPositiveLimit", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Expired-window counter cleanup", "TooManyAttempts", "TooManyAttempts", "demo:ratelimit expired-window", "expired-window", "TestRateLimitDemoExpiredWindow", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Remaining attempts and RetriesLeft alias", "Remaining / RetriesLeft", "Remaining / RetriesLeft", "demo:ratelimit remaining", "remaining", "TestRateLimitDemoRemaining", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Remaining attempts lower bound", "Remaining / RetriesLeft", "Remaining / RetriesLeft", "demo:ratelimit remaining-floor", "remaining-floor", "TestRateLimitDemoRemainingFloor", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Seconds until availability", "AvailableIn", "AvailableIn", "demo:ratelimit available-in", "available-in", "TestRateLimitDemoAvailableIn", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Elapsed availability lower bound", "AvailableIn", "AvailableIn", "demo:ratelimit available-in-elapsed", "available-in-elapsed", "TestRateLimitDemoAvailableInElapsed", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Reset attempts while preserving timer", "ResetAttempts", "ResetAttempts / Clear", "demo:ratelimit reset-attempts", "reset-attempts", "TestRateLimitDemoResetAttempts", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Clear attempts and timer", "Clear", "ResetAttempts / Clear", "demo:ratelimit clear", "clear", "TestRateLimitDemoClear", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Successful atomic attempt", "Attempt", "Attempt", "demo:ratelimit attempt-success", "attempt-success", "TestRateLimitDemoAttemptSuccess", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Blocked atomic attempt", "Attempt", "Attempt", "demo:ratelimit attempt-blocked", "attempt-blocked", "TestRateLimitDemoAttemptBlocked", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Failed callback is not counted", "Attempt", "Attempt", "demo:ratelimit attempt-error", "attempt-error", "TestRateLimitDemoAttemptError", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Nil atomic-attempt callback", "Attempt", "Attempt", "demo:ratelimit attempt-nil", "attempt-nil", "TestRateLimitDemoAttemptNil", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Control-character key cleaning", "CleanRateLimiterKey", "CleanRateLimiterKey", "demo:ratelimit clean-key", "clean-key", "TestRateLimitDemoCleanKey", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Hashed middleware dimension keys", "哈希 key", "Hashed Keys", "demo:ratelimit hashed-key", "hashed-key", "TestRateLimitDemoHashedKey", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Plain middleware dimension keys", "哈希 key", "Hashed Keys", "demo:ratelimit unhashed-key", "unhashed-key", "TestRateLimitDemoUnhashedKey", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Manual keys remain caller-controlled", "哈希 key", "Hashed Keys", "demo:ratelimit manual-key", "manual-key", "TestRateLimitDemoManualKey", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Business and isolation key design", "设计原则", "Key Design", "demo:ratelimit key-design", "key-design", "TestRateLimitDemoKeyDesign", LevelCompile, StatusPlanned),
		baselineEntry("ratelimit", "Counter and timer cache layout", "工作机制", "How It Works", "demo:ratelimit cache-layout", "cache-layout", "TestRateLimitDemoCacheLayout", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Fixed-window lifecycle", "判断流程", "How It Works", "demo:ratelimit fixed-window", "fixed-window", "TestRateLimitDemoFixedWindow", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Middleware cache key format", "中间件 key 格式", "How It Works", "demo:ratelimit middleware-key", "middleware-key", "TestRateLimitDemoMiddlewareKey", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Cache operation error propagation", "错误处理", "Error Handling", "demo:ratelimit cache-errors", "cache-errors", "TestRateLimitDemoCacheErrors", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Redis connection error propagation", "错误处理", "Error Handling", "demo:ratelimit redis-errors --store=redis", "redis-errors", "TestRateLimitDemoRedisErrors", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("ratelimit", "Non-integer counter errors", "错误处理", "Error Handling", "demo:ratelimit counter-type-error", "counter-type-error", "TestRateLimitDemoCounterTypeError", LevelHermetic, StatusPlanned),
		baselineEntry("ratelimit", "Fail-open or fail-closed error policy", "推荐处理方式", "Error Handling", "demo:ratelimit error-policy", "error-policy", "TestRateLimitDemoErrorPolicy", LevelCompile, StatusPlanned),
		baselineEntry("ratelimit", "Laravel 13 compatibility boundaries", "与 Laravel 13 的边界", "Boundaries Compared With Laravel 13", "demo:ratelimit laravel-compatibility", "laravel-compatibility", "TestRateLimitDemoLaravelCompatibility", LevelCompile, StatusPlanned),
	}
}
