package catalog

func redisEntries() []Entry {
	return []Entry{
		baselineEntry("redis", "Native client and managed connection architecture", "简介", "Introduction", "demo:redis architecture", "architecture", "TestRedisDemoArchitecture", LevelCompile, StatusPlanned),
		baselineEntry("redis", "Basic database.redis configuration", "基本配置", "Basic Configuration", "demo:redis config", "config", "TestRedisDemoConfiguration", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Supported client identifiers", "基本配置", "Basic Configuration", "demo:redis client-identifiers", "client-identifiers", "TestRedisDemoClientIdentifiers", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Named connection configuration", "基本配置", "Basic Configuration", "demo:redis named-config", "named-config", "TestRedisDemoNamedConfiguration", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Address configuration and precedence", "连接参数说明", "Connection Parameters", "demo:redis address-precedence", "address-precedence", "TestRedisDemoAddressPrecedence", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Database number aliases and precedence", "连接参数说明", "Connection Parameters", "demo:redis database-precedence", "database-precedence", "TestRedisDemoDatabasePrecedence", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Authentication configuration and precedence", "连接参数说明", "Connection Parameters", "demo:redis authentication", "authentication", "TestRedisDemoAuthenticationConfiguration", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "URL connection parsing and overrides", "URL 连接方式", "URL Connection", "demo:redis url", "url", "TestRedisDemoURLConfiguration", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "TLS connection configuration", "高级连接选项", "Advanced Connection Options", "demo:redis tls", "tls", "TestRedisDemoTLSConfiguration", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Redis client naming", "高级连接选项", "Advanced Connection Options", "demo:redis client-name", "client-name", "TestRedisDemoClientNameConfiguration", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Dial, read, and write timeout parsing", "高级连接选项", "Advanced Connection Options", "demo:redis timeouts", "timeouts", "TestRedisDemoTimeoutConfiguration", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Maximum retry configuration", "高级连接选项", "Advanced Connection Options", "demo:redis max-retries", "max-retries", "TestRedisDemoMaxRetriesConfiguration", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Redis environment variable configuration", "环境变量参考", "Environment Variables Reference", "demo:redis environment", "environment", "TestRedisDemoEnvironmentConfiguration", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Default Facade client resolution", "获取客户端", "Obtaining a Client", "demo:redis client", "client", "TestRedisDemoDefaultClient", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Named Facade client resolution", "获取客户端", "Obtaining a Client", "demo:redis named-client", "named-client", "TestRedisDemoNamedClient", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Facade Connection resolution and metadata", "获取客户端", "Obtaining a Client", "demo:redis connection", "connection", "TestRedisDemoConnection", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "String commands", "执行 Redis 命令", "Executing Redis Commands", "demo:redis strings", "strings", "TestRedisDemoStringCommands", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Hash commands", "执行 Redis 命令", "Executing Redis Commands", "demo:redis hashes", "hashes", "TestRedisDemoHashCommands", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "List commands", "执行 Redis 命令", "Executing Redis Commands", "demo:redis lists", "lists", "TestRedisDemoListCommands", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Set commands", "执行 Redis 命令", "Executing Redis Commands", "demo:redis sets", "sets", "TestRedisDemoSetCommands", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Sorted set commands", "执行 Redis 命令", "Executing Redis Commands", "demo:redis sorted-sets", "sorted-sets", "TestRedisDemoSortedSetCommands", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Atomic counter commands", "执行 Redis 命令", "Executing Redis Commands", "demo:redis counters", "counters", "TestRedisDemoCounterCommands", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Key existence, expiration, and deletion", "执行 Redis 命令", "Executing Redis Commands", "demo:redis keys", "keys", "TestRedisDemoKeyCommands", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Native go-redis command surface", "执行 Redis 命令", "Executing Redis Commands", "demo:redis native-client", "native-client", "TestRedisDemoNativeClientContract", LevelCompile, StatusPlanned),
		baselineEntry("redis", "MULTI/EXEC transactions", "事务", "Transactions", "demo:redis transaction", "transaction", "TestRedisDemoTransaction", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Atomic Lua scripts", "Lua 脚本", "Lua Scripts", "demo:redis lua", "lua", "TestRedisDemoLuaScript", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Pipeline command batching and results", "管道命令", "Pipelining Commands", "demo:redis pipeline", "pipeline", "TestRedisDemoPipeline", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Publishing messages", "发布 / 订阅", "Pub / Sub", "demo:redis publish", "publish", "TestRedisDemoPublish", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Channel subscriptions", "发布 / 订阅", "Pub / Sub", "demo:redis subscribe", "subscribe", "TestRedisDemoSubscribe", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Pattern subscriptions", "发布 / 订阅", "Pub / Sub", "demo:redis psubscribe", "psubscribe", "TestRedisDemoPatternSubscribe", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Manager construction from explicit configuration", "创建 Manager", "Creating a Manager", "demo:redis manager", "manager", "TestRedisDemoManagerConstruction", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Manager construction from a config repository", "创建 Manager", "Creating a Manager", "demo:redis manager-repository", "manager-repository", "TestRedisDemoManagerFromRepository", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Manager construction from the Application Facade", "创建 Manager", "Creating a Manager", "demo:redis manager-application", "manager-application", "TestRedisDemoManagerFromApplication", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Default named connection resolution", "获取连接", "Obtaining Connections", "demo:redis default-connection", "default-connection", "TestRedisDemoDefaultConnection", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Explicit named connection resolution", "获取连接", "Obtaining Connections", "demo:redis named-connection", "named-connection", "TestRedisDemoNamedConnection", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Explicit DefaultConnection resolution", "获取连接", "Obtaining Connections", "demo:redis default-connection-method", "default-connection-method", "TestRedisDemoDefaultConnectionMethod", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Lazy connection creation", "获取连接", "Obtaining Connections", "demo:redis lazy-connection", "lazy-connection", "TestRedisDemoLazyConnectionCreation", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Multiple isolated named connections", "多连接切换", "Multiple Connections", "demo:redis multiple-connections", "multiple-connections", "TestRedisDemoMultipleConnections", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Same-name connection reuse", "连接重用与缓存", "Connection Reuse and Caching", "demo:redis connection-reuse", "connection-reuse", "TestRedisDemoConnectionReuse", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Resolved connection snapshots", "连接重用与缓存", "Connection Reuse and Caching", "demo:redis connections-snapshot", "connections-snapshot", "TestRedisDemoConnectionsSnapshot", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Connection snapshots do not resolve new clients", "连接重用与缓存", "Connection Reuse and Caching", "demo:redis snapshot-lazy", "snapshot-lazy", "TestRedisDemoConnectionSnapshotIsLazy", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Purging named connections", "连接重建", "Purging Connections", "demo:redis purge", "purge", "TestRedisDemoPurge", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Rebuilding purged connections", "连接重建", "Purging Connections", "demo:redis purge-rebuild", "purge-rebuild", "TestRedisDemoPurgeRebuild", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Closing resolved connections", "关闭连接", "Closing Connections", "demo:redis close", "close", "TestRedisDemoClose", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Continuing after connection close errors", "关闭连接", "Closing Connections", "demo:redis close-errors", "close-errors", "TestRedisDemoCloseErrors", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Context-cancelled close retry state", "关闭连接", "Closing Connections", "demo:redis close-cancellation", "close-cancellation", "TestRedisDemoCloseCancellation", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Successful command events", "事件类型", "Event Types", "demo:redis command-executed-event", "command-executed-event", "TestRedisDemoCommandExecutedEvent", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Failed command events", "事件类型", "Event Types", "demo:redis command-failed-event", "command-failed-event", "TestRedisDemoCommandFailedEvent", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Successful batch command events", "事件类型", "Event Types", "demo:redis batch-executed-event", "batch-executed-event", "TestRedisDemoBatchExecutedEvent", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Failed batch command events", "事件类型", "Event Types", "demo:redis batch-failed-event", "batch-failed-event", "TestRedisDemoBatchFailedEvent", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Command and batch event payload snapshots", "事件类型", "Event Types", "demo:redis event-payloads", "event-payloads", "TestRedisDemoEventPayloads", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Sensitive event parameter handling", "事件类型", "Event Types", "demo:redis event-sensitive-parameters", "event-sensitive-parameters", "TestRedisDemoEventSensitiveParameters", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Global successful command listeners", "全局事件监听", "Global Event Listeners", "demo:redis global-command-listener", "global-command-listener", "TestRedisDemoGlobalCommandListener", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Global failed command listeners", "全局事件监听", "Global Event Listeners", "demo:redis global-failure-listener", "global-failure-listener", "TestRedisDemoGlobalFailureListener", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Global batch command listeners", "全局事件监听", "Global Event Listeners", "demo:redis global-batch-listener", "global-batch-listener", "TestRedisDemoGlobalBatchListener", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Connection-level success listeners", "连接级监听器", "Connection-Level Listeners", "demo:redis connection-listener", "connection-listener", "TestRedisDemoConnectionListener", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Connection-level failure listeners", "连接级监听器", "Connection-Level Listeners", "demo:redis connection-failure-listener", "connection-failure-listener", "TestRedisDemoConnectionFailureListener", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Listener panic isolation and reporting", "连接级监听器", "Connection-Level Listeners", "demo:redis listener-panic", "listener-panic", "TestRedisDemoListenerPanicIsolation", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Disabling command events", "关闭事件", "Disabling Events", "demo:redis disable-events", "disable-events", "TestRedisDemoDisableEvents", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Re-enabling events for existing and future connections", "关闭事件", "Disabling Events", "demo:redis enable-events", "enable-events", "TestRedisDemoEnableEvents", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "ServiceProvider container bindings", "ServiceProvider 注册", "ServiceProvider Registration", "demo:redis provider-registration", "provider-registration", "TestRedisDemoProviderRegistration", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "ServiceProvider event bridge boot", "ServiceProvider 注册", "ServiceProvider Registration", "demo:redis provider-event-bridge", "provider-event-bridge", "TestRedisDemoProviderEventBridge", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Redis Factory container resolution", "容器解析", "Container Resolution", "demo:redis container-factory", "container-factory", "TestRedisDemoContainerFactory", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Default Connection container resolution", "容器解析", "Container Resolution", "demo:redis container-connection", "container-connection", "TestRedisDemoContainerConnection", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Named Connection resolution through Factory", "容器解析", "Container Resolution", "demo:redis container-named-connection", "container-named-connection", "TestRedisDemoContainerNamedConnection", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Automatic container lifecycle shutdown", "生命周期关闭", "Lifecycle Shutdown", "demo:redis lifecycle-close", "lifecycle-close", "TestRedisDemoLifecycleClose", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Cache driver connection integration", "缓存驱动", "Cache Driver", "demo:redis cache-driver", "cache-driver", "TestRedisDemoCacheDriver", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Redis cache basic reads and writes", "缓存驱动", "Cache Driver", "demo:redis cache-basic", "cache-basic", "TestRedisDemoCacheBasicOperations", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Redis cache TTL management", "缓存驱动", "Cache Driver", "demo:redis cache-ttl", "cache-ttl", "TestRedisDemoCacheTTL", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Redis cache atomic operations", "缓存驱动", "Cache Driver", "demo:redis cache-atomic", "cache-atomic", "TestRedisDemoCacheAtomicOperations", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Redis cache bulk operations", "缓存驱动", "Cache Driver", "demo:redis cache-bulk", "cache-bulk", "TestRedisDemoCacheBulkOperations", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Redis tagged cache operations", "缓存驱动", "Cache Driver", "demo:redis cache-tags", "cache-tags", "TestRedisDemoCacheTags", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Redis cache prefix-aware flush", "缓存驱动", "Cache Driver", "demo:redis cache-flush", "cache-flush", "TestRedisDemoCacheFlush", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Queue driver connection integration", "队列驱动", "Queue Driver", "demo:redis queue-driver", "queue-driver", "TestRedisDemoQueueDriver", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Ready-list queue dispatch", "队列驱动", "Queue Driver", "demo:redis queue-ready", "queue-ready", "TestRedisDemoQueueReadyList", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Delayed sorted-set queue dispatch", "队列驱动", "Queue Driver", "demo:redis queue-delayed", "queue-delayed", "TestRedisDemoQueueDelayedSet", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Blocking queue pop", "队列驱动", "Queue Driver", "demo:redis queue-blocking-pop", "queue-blocking-pop", "TestRedisDemoQueueBlockingPop", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Failed job storage", "队列驱动", "Queue Driver", "demo:redis queue-failed", "queue-failed", "TestRedisDemoQueueFailedStore", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Horizon Redis store configuration", "Horizon 存储", "Horizon Storage", "demo:redis horizon-config", "horizon-config", "TestRedisDemoHorizonConfiguration", LevelHermetic, StatusPlanned),
		baselineEntry("redis", "Horizon process heartbeats and leases", "Horizon 存储", "Horizon Storage", "demo:redis horizon-processes", "horizon-processes", "TestRedisDemoHorizonProcesses", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Horizon global control flags", "Horizon 存储", "Horizon Storage", "demo:redis horizon-control", "horizon-control", "TestRedisDemoHorizonControl", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Horizon event metric windows", "Horizon 存储", "Horizon Storage", "demo:redis horizon-metrics", "horizon-metrics", "TestRedisDemoHorizonMetrics", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Horizon queue length snapshots", "Horizon 存储", "Horizon Storage", "demo:redis horizon-queue-lengths", "horizon-queue-lengths", "TestRedisDemoHorizonQueueLengths", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Horizon batch-safe summaries", "Horizon 存储", "Horizon Storage", "demo:redis horizon-summaries", "horizon-summaries", "TestRedisDemoHorizonSummaries", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Horizon high-value job diagnostics", "Horizon 存储", "Horizon Storage", "demo:redis horizon-job-diagnostics", "horizon-job-diagnostics", "TestRedisDemoHorizonJobDiagnostics", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Horizon observability diagnostics", "Horizon 存储", "Horizon Storage", "demo:redis horizon-observability", "horizon-observability", "TestRedisDemoHorizonObservability", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Horizon orphan process tracking", "Horizon 存储", "Horizon Storage", "demo:redis horizon-orphans", "horizon-orphans", "TestRedisDemoHorizonOrphans", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("redis", "Facade Resolve and ManagerInstance access", "Facade 参考", "Facade Reference", "demo:redis facade-manager", "facade-manager", "TestRedisDemoFacadeManagerAccess", LevelCompile, StatusPlanned),
		baselineEntry("redis", "Facade ManagerCloseOption binding", "Facade 参考", "Facade Reference", "demo:redis manager-close-option", "manager-close-option", "TestRedisDemoManagerCloseOption", LevelCompile, StatusPlanned),
		baselineEntry("redis", "Manager Factory interface contract", "Manager 接口参考", "Manager Interface Reference", "demo:redis manager-contract", "manager-contract", "TestRedisDemoManagerContract", LevelCompile, StatusPlanned),
		baselineEntry("redis", "Connection interface contract", "Connection 接口参考", "Connection Interface Reference", "demo:redis connection-contract", "connection-contract", "TestRedisDemoConnectionContract", LevelCompile, StatusPlanned),
		baselineEntry("redis", "Redis event type aliases", "事件类型参考", "Event Types Reference", "demo:redis event-aliases", "event-aliases", "TestRedisDemoEventAliases", LevelCompile, StatusPlanned),
		baselineEntry("redis", "Event bus wrapper types and names", "事件类型参考", "Event Types Reference", "demo:redis event-wrappers", "event-wrappers", "TestRedisDemoEventWrappers", LevelCompile, StatusPlanned),
	}
}
