package catalog

func routeEntries() []Entry {
	return []Entry{
		baselineEntry("route", "Declarative router architecture", "简介", "Introduction", "demo:route architecture", "architecture", "TestRouteDemoArchitecture", LevelCompile, StatusImplemented),
		baselineEntry("route", "Package-level facade registration", "使用 Facade（推荐）", "Quick Start", "demo:route facade", "facade", "TestRouteDemoFacade", LevelScenario, StatusImplemented),
		baselineEntry("route", "Mounting declarations to Gin", "挂载到 Gin Engine", "Quick Start", "demo:route mount", "mount", "TestRouteDemoMount", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Isolated Router instances", "使用独立 Router 实例", "Quick Start", "demo:route isolated-router", "isolated-router", "TestRouteDemoIsolatedRouter", LevelHermetic, StatusImplemented),
		baselineEntry("route", "HTTP method route registration", "注册 HTTP 方法路由", "Basic Routing", "demo:route http-methods", "http-methods", "TestRouteDemoHTTPMethods", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Multi-method Match registration", "多个 HTTP 方法共用一个 Handler", "Basic Routing", "demo:route match", "match", "TestRouteDemoMatch", LevelHermetic, StatusImplemented),
		baselineEntry("route", "All common HTTP methods", "注册所有常见 HTTP 方法", "Basic Routing", "demo:route any", "any", "TestRouteDemoAny", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Laravel-style route parameters", "参数写法", "Route Parameters", "demo:route laravel-parameters", "laravel-parameters", "TestRouteDemoLaravelParameters", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Native Gin route parameters", "参数写法", "Route Parameters", "demo:route gin-parameters", "gin-parameters", "TestRouteDemoGinParameters", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Reading parameters in handlers", "参数写法", "Route Parameters", "demo:route parameter-read", "parameter-read", "TestRouteDemoParameterRead", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Optional route parameters", "可选参数", "Route Parameters", "demo:route optional-parameters", "optional-parameters", "TestRouteDemoOptionalParameters", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Wildcard route parameters", "通配参数", "Route Parameters", "demo:route wildcard-parameters", "wildcard-parameters", "TestRouteDemoWildcardParameters", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Custom regular-expression constraints", "单条路由约束", "Parameter Constraints", "demo:route where", "where", "TestRouteDemoWhere", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Numeric parameter constraints", "约束方法速查", "Parameter Constraints", "demo:route where-number", "where-number", "TestRouteDemoWhereNumber", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Alphabetic parameter constraints", "约束方法速查", "Parameter Constraints", "demo:route where-alpha", "where-alpha", "TestRouteDemoWhereAlpha", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Alphanumeric parameter constraints", "约束方法速查", "Parameter Constraints", "demo:route where-alphanumeric", "where-alphanumeric", "TestRouteDemoWhereAlphaNumeric", LevelHermetic, StatusImplemented),
		baselineEntry("route", "UUID parameter constraints", "约束方法速查", "Parameter Constraints", "demo:route where-uuid", "where-uuid", "TestRouteDemoWhereUUID", LevelHermetic, StatusImplemented),
		baselineEntry("route", "ULID parameter constraints", "约束方法速查", "Parameter Constraints", "demo:route where-ulid", "where-ulid", "TestRouteDemoWhereULID", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Enumerated parameter constraints", "约束方法速查", "Parameter Constraints", "demo:route where-in", "where-in", "TestRouteDemoWhereIn", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Group parameter constraints", "分组约束", "Parameter Constraints", "demo:route group-constraints", "group-constraints", "TestRouteDemoGroupConstraints", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Global parameter patterns", "全局参数约束", "Parameter Constraints", "demo:route global-pattern", "global-pattern", "TestRouteDemoGlobalPattern", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Route constraints overriding global patterns", "全局参数约束", "Parameter Constraints", "demo:route constraint-override", "constraint-override", "TestRouteDemoConstraintOverride", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Named route registration", "给路由命名", "Named Routes", "demo:route route-name", "route-name", "TestRouteDemoName", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Named route URL generation", "生成 URL", "Named Routes", "demo:route url", "url", "TestRouteDemoURL", LevelHermetic, StatusImplemented),
		baselineEntry("route", "URL parameter path escaping", "生成 URL", "Named Routes", "demo:route url-escaping", "url-escaping", "TestRouteDemoURLEscaping", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Missing URL parameter errors", "生成 URL", "Named Routes", "demo:route url-missing-parameter", "url-missing-parameter", "TestRouteDemoURLMissingParameter", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Group route-name prefixes", "分组命名前缀", "Named Routes", "demo:route group-name-prefix", "group-name-prefix", "TestRouteDemoGroupNamePrefix", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Repeated route naming semantics", "重复命名", "Named Routes", "demo:route duplicate-route-name", "duplicate-route-name", "TestRouteDemoDuplicateName", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Group path prefixes", "路径前缀", "Route Groups", "demo:route group-prefix", "group-prefix", "TestRouteDemoGroupPrefix", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Chained group attributes", "链式组合", "Route Groups", "demo:route group-chain", "group-chain", "TestRouteDemoGroupChain", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Nested group inheritance", "嵌套分组", "Route Groups", "demo:route nested-groups", "nested-groups", "TestRouteDemoNestedGroups", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Group middleware", "分组中间件", "Middleware", "demo:route group-middleware", "group-middleware", "TestRouteDemoGroupMiddleware", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Route-level middleware", "路由级中间件", "Middleware", "demo:route route-middleware", "route-middleware", "TestRouteDemoRouteMiddleware", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Stable named middleware", "命名中间件与排除", "Middleware", "demo:route named-middleware", "named-middleware", "TestRouteDemoNamedMiddleware", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Unnamed middleware function-name fallback", "命名中间件与排除", "Middleware", "demo:route middleware-function-name", "middleware-function-name", "TestRouteDemoMiddlewareFunctionName", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Route-level middleware exclusion", "命名中间件与排除", "Middleware", "demo:route route-without-middleware", "route-without-middleware", "TestRouteDemoRouteWithoutMiddleware", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Registrar-level middleware exclusion", "命名中间件与排除", "Middleware", "demo:route registrar-without-middleware", "registrar-without-middleware", "TestRouteDemoRegistrarWithoutMiddleware", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Parameter binder registration", "注册绑定器", "Parameter Binding", "demo:route bind", "bind", "TestRouteDemoBind", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Model binder alias", "注册绑定器", "Parameter Binding", "demo:route model", "model", "TestRouteDemoModel", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Bound object context access", "在 Handler 中读取绑定结果", "Parameter Binding", "demo:route binding-context", "binding-context", "TestRouteDemoBindingContext", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Custom binding failure handlers", "绑定失败处理", "Parameter Binding", "demo:route missing-handler", "missing-handler", "TestRouteDemoMissingHandler", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Default binding failure response", "绑定失败处理", "Parameter Binding", "demo:route default-missing", "default-missing", "TestRouteDemoDefaultMissing", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Controller action registration", "控制器 Action", "Controller Actions", "demo:route controller-action", "controller-action", "TestRouteDemoControllerAction", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Controller action validation panics", "控制器 Action", "Controller Actions", "demo:route controller-validation", "controller-validation", "TestRouteDemoControllerValidation", LevelHermetic, StatusImplemented),
		baselineEntry("route", "API resource routes", "API 资源路由", "Resource Routes", "demo:route api-resource", "api-resource", "TestRouteDemoAPIResource", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Full resource routes", "完整资源路由（含页面型动作）", "Resource Routes", "demo:route resource", "resource", "TestRouteDemoResource", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Optional resource Create action", "完整资源路由（含页面型动作）", "Resource Routes", "demo:route resource-create", "resource-create", "TestRouteDemoResourceCreate", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Optional resource Edit action", "完整资源路由（含页面型动作）", "Resource Routes", "demo:route resource-edit", "resource-edit", "TestRouteDemoResourceEdit", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Resource Only option", "资源路由选项", "Resource Routes", "demo:route resource-only", "resource-only", "TestRouteDemoResourceOnly", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Resource Except option", "资源路由选项", "Resource Routes", "demo:route resource-except", "resource-except", "TestRouteDemoResourceExcept", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Resource route-name customization", "资源路由选项", "Resource Routes", "demo:route resource-names", "resource-names", "TestRouteDemoResourceNames", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Resource parameter customization", "资源路由选项", "Resource Routes", "demo:route resource-parameters", "resource-parameters", "TestRouteDemoResourceParameters", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Bulk API resource registration", "批量注册 API 资源", "Resource Routes", "demo:route api-resources", "api-resources", "TestRouteDemoAPIResources", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Nested resource paths", "嵌套资源", "Resource Routes", "demo:route nested-resource", "nested-resource", "TestRouteDemoNestedResource", LevelHermetic, StatusImplemented),
		baselineEntry("route", "ResourceController interface contract", "接口", "Resource Route API Reference", "demo:route resource-controller-contract", "resource-controller-contract", "TestRouteDemoResourceControllerContract", LevelCompile, StatusImplemented),
		baselineEntry("route", "CreateController interface contract", "接口", "Resource Route API Reference", "demo:route create-controller-contract", "create-controller-contract", "TestRouteDemoCreateControllerContract", LevelCompile, StatusImplemented),
		baselineEntry("route", "EditController interface contract", "接口", "Resource Route API Reference", "demo:route edit-controller-contract", "edit-controller-contract", "TestRouteDemoEditControllerContract", LevelCompile, StatusImplemented),
		baselineEntry("route", "Default and custom temporary redirects", "重定向路由", "Redirect Routes", "demo:route redirect", "redirect", "TestRouteDemoRedirect", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Permanent redirects", "重定向路由", "Redirect Routes", "demo:route permanent-redirect", "permanent-redirect", "TestRouteDemoPermanentRedirect", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Static file routes", "静态文件", "Static Files", "demo:route static", "static", "TestRouteDemoStatic", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Fallback routes", "Fallback 路由", "Fallback Routes", "demo:route fallback", "fallback", "TestRouteDemoFallback", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Exact domain constraints", "域名约束", "Domain Constraints", "demo:route domain", "domain", "TestRouteDemoDomain", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Placeholder subdomain constraints", "域名约束", "Domain Constraints", "demo:route domain-placeholder", "domain-placeholder", "TestRouteDemoDomainPlaceholder", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Named rate limiter registration", "注册限流器", "Rate Limiting", "demo:route rate-limiter", "rate-limiter", "TestRouteDemoRateLimiter", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Limit window and key construction", "限流 API 参考", "Rate Limiting API Reference", "demo:route limit", "limit", "TestRouteDemoLimit", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Route-level throttling", "挂载到路由", "Rate Limiting", "demo:route throttle-route", "throttle-route", "TestRouteDemoThrottleRoute", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Group-level throttling", "挂载到路由", "Rate Limiting", "demo:route throttle-group", "throttle-group", "TestRouteDemoThrottleGroup", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Unknown limiter pass-through", "挂载到路由", "Rate Limiting", "demo:route throttle-unknown", "throttle-unknown", "TestRouteDemoThrottleUnknown", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Over-limit status and response", "挂载到路由", "Rate Limiting", "demo:route throttle-over-limit", "throttle-over-limit", "TestRouteDemoThrottleOverLimit", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Current route context injection", "当前路由信息", "Current Route Information", "demo:route current-route", "current-route", "TestRouteDemoCurrentRoute", LevelHermetic, StatusImplemented),
		baselineEntry("route", "RouteInfo metadata contract", "RouteInfo 结构体", "Current Route Information", "demo:route route-info", "route-info", "TestRouteDemoRouteInfo", LevelCompile, StatusImplemented),
		baselineEntry("route", "Route list snapshots", "代码中查看", "Route List and Debugging", "demo:route list-entries", "list", "TestRouteDemoList", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Route-list command filters", "命令行查看", "Route List and Debugging", "demo:route list-command", "list-command", "TestRouteDemoListCommand", LevelScenario, StatusImplemented),
		baselineEntry("route", "Handler execution order", "处理器执行顺序", "Handler Execution Order", "demo:route handler-order", "handler-order", "TestRouteDemoHandlerOrder", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Global Router resolution", "获取全局 Router", "Global Facade Lifecycle", "demo:route resolve", "resolve", "TestRouteDemoResolve", LevelScenario, StatusImplemented),
		baselineEntry("route", "Router state reset", "测试隔离", "Global Facade Lifecycle", "demo:route reset", "reset", "TestRouteDemoReset", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Deep-cloned route tables", "构造函数", "Router API Reference", "demo:route clone", "clone", "TestRouteDemoClone", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Low-level Add registration", "路由注册", "Router API Reference", "demo:route add", "add", "TestRouteDemoAdd", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Direct Router grouping", "声明器入口", "Router API Reference", "demo:route router-group", "router-group", "TestRouteDemoRouterGroup", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Route scoped-binding compatibility", "Route 链式配置 API 参考", "Route Chain API Reference", "demo:route route-scope-bindings", "route-scope-bindings", "TestRouteDemoRouteScopeBindings", LevelCompile, StatusImplemented),
		baselineEntry("route", "Registrar scoped-binding compatibility", "属性设置", "Registrar API Reference", "demo:route registrar-scope-bindings", "registrar-scope-bindings", "TestRouteDemoRegistrarScopeBindings", LevelCompile, StatusImplemented),
		baselineEntry("route", "Registrar controller and domain override semantics", "属性设置", "Registrar API Reference", "demo:route registrar-overrides", "registrar-overrides", "TestRouteDemoRegistrarOverrides", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Global facade API surface", "全局 Facade 函数速查", "Global Facade Function Reference", "demo:route facade-contract", "facade-contract", "TestRouteDemoFacadeContract", LevelCompile, StatusImplemented),
		baselineEntry("route", "ServiceProvider lazy registration", "ServiceProvider", "ServiceProvider", "demo:route provider-registration", "provider-registration", "TestRouteDemoProviderRegistration", LevelScenario, StatusImplemented),
		baselineEntry("route", "ServiceProvider preserves injected routers", "ServiceProvider", "ServiceProvider", "demo:route provider-preserves-router", "provider-preserves-router", "TestRouteDemoProviderPreservesRouter", LevelHermetic, StatusImplemented),
		baselineEntry("route", "ServiceProvider singleton resolution", "ServiceProvider", "ServiceProvider", "demo:route provider-singleton", "provider-singleton", "TestRouteDemoProviderSingleton", LevelHermetic, StatusImplemented),
		baselineEntry("route", "Recommended project route organization", "项目内推荐写法", "Recommended Project Usage", "demo:route best-practices", "best-practices", "TestRouteDemoBestPractices", LevelCompile, StatusImplemented),
	}
}
