package catalog

func schemaEntries() []Entry {
	return []Entry{
		baselineEntry("schema", "Schema builder architecture and supported dialects", "简介", "Introduction", "demo:schema architecture", "architecture", "TestSchemaDemoArchitecture", LevelCompile, StatusPlanned),
		baselineEntry("schema", "Optional SQLite dialect registration", "简介", "Introduction", "demo:schema sqlite-extension", "sqlite-extension", "TestSchemaDemoSQLiteExtension", LevelCompile, StatusPlanned),
		baselineEntry("schema", "SQLite pinned-connection and serial migration requirements", "简介", "Introduction", "demo:schema sqlite-connection-scope", "sqlite-connection-scope", "TestSchemaDemoSQLiteConnectionScope", LevelCompile, StatusPlanned),
		baselineEntry("schema", "Default string length configuration", "配置参数说明", "Configuration Parameters", "demo:schema default-string-length", "default-string-length", "TestSchemaDemoDefaultStringLength", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Default time precision configuration", "配置参数说明", "Configuration Parameters", "demo:schema default-time-precision", "default-time-precision", "TestSchemaDemoDefaultTimePrecision", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Default morph key type configuration", "配置参数说明", "Configuration Parameters", "demo:schema default-morph-key-type", "default-morph-key-type", "TestSchemaDemoDefaultMorphKeyType", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "UUID morph key shortcut", "配置参数说明", "Configuration Parameters", "demo:schema morph-using-uuids", "morph-using-uuids", "TestSchemaDemoMorphUsingUUIDs", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "ULID morph key shortcut", "配置参数说明", "Configuration Parameters", "demo:schema morph-using-ulids", "morph-using-ulids", "TestSchemaDemoMorphUsingULIDs", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Explicit GORM tag precedence over schema defaults", "配置参数说明", "Configuration Parameters", "demo:schema explicit-tag-precedence", "explicit-tag-precedence", "TestSchemaDemoExplicitTagPrecedence", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Migration connection binding", "绑定迁移连接", "Binding a Migration Connection", "demo:schema bind", "bind", "TestSchemaDemoBind", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Standalone Builder construction", "`New` 构造函数", "The `New` Constructor", "demo:schema new", "new", "TestSchemaDemoNew", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Named connection selection and deferred errors", "指定命名连接", "Specifying a Named Connection", "demo:schema named-connection", "named-connection", "TestSchemaDemoNamedConnection", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Package-level facade operations", "包级 Facade", "Package-Level Facade", "demo:schema facade", "facade", "TestSchemaDemoFacade", LevelScenario, StatusPlanned),
		baselineEntry("schema", "Declarative table creation", "创建数据表", "Creating Tables", "demo:schema create", "create", "TestSchemaDemoCreate", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Create idempotency and empty-blueprint validation", "创建数据表", "Creating Tables", "demo:schema create-validation", "create-validation", "TestSchemaDemoCreateValidation", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Create table dialect options", "创建数据表", "Creating Tables", "demo:schema create-dialect-options", "create-dialect-options", "TestSchemaDemoCreateDialectOptions", LevelCompile, StatusPlanned),
		baselineEntry("schema", "Existing table alteration", "修改数据表", "Updating Tables", "demo:schema table", "table", "TestSchemaDemoTable", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Idempotent column addition", "新增字段", "Adding Columns", "demo:schema add-column", "add-column", "TestSchemaDemoAddColumn", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Column modification and dialect boundary", "修改字段", "Modifying Columns", "demo:schema change-column", "change-column", "TestSchemaDemoChangeColumn", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Idempotent column renaming", "重命名字段", "Renaming Columns", "demo:schema rename-column", "rename-column", "TestSchemaDemoRenameColumn", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Variadic column dropping", "删除字段", "Dropping Columns", "demo:schema drop-column", "drop-column", "TestSchemaDemoDropColumn", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Slice-based column dropping", "删除字段", "Dropping Columns", "demo:schema drop-columns", "drop-columns", "TestSchemaDemoDropColumns", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Raw structural SQL commands", "原始 SQL 命令", "Raw SQL Commands", "demo:schema raw", "raw", "TestSchemaDemoRaw", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Idempotent table renaming", "重命名与删除", "Renaming / Dropping", "demo:schema rename", "rename", "TestSchemaDemoRename", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Table dropping aliases", "重命名与删除", "Renaming / Dropping", "demo:schema drop", "drop", "TestSchemaDemoDrop", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Builder-level column dropping", "重命名与删除", "Renaming / Dropping", "demo:schema builder-drop-columns", "builder-drop-columns", "TestSchemaDemoBuilderDropColumns", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Dropping all tables with foreign key safety", "危险清理操作", "Destructive Operations", "demo:schema drop-all-tables", "drop-all-tables", "TestSchemaDemoDropAllTables", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Dropping all views", "危险清理操作", "Destructive Operations", "demo:schema drop-all-views", "drop-all-views", "TestSchemaDemoDropAllViews", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Dropping all user-defined types", "危险清理操作", "Destructive Operations", "demo:schema drop-all-types", "drop-all-types", "TestSchemaDemoDropAllTypes", LevelCompile, StatusPlanned),
		baselineEntry("schema", "Default and named ID columns", "主键与自增", "Primary Keys & Increments", "demo:schema id", "id", "TestSchemaDemoID", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Integer auto-increment column families", "主键与自增", "Primary Keys & Increments", "demo:schema increments", "increments", "TestSchemaDemoIncrements", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Signed integer column families", "主键与自增", "Primary Keys & Increments", "demo:schema signed-integers", "signed-integers", "TestSchemaDemoSignedIntegers", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Unsigned integer column families", "主键与自增", "Primary Keys & Increments", "demo:schema unsigned-integers", "unsigned-integers", "TestSchemaDemoUnsignedIntegers", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Variable and fixed-length string columns", "字符串与文本类型", "String & Text Types", "demo:schema string-char", "string-char", "TestSchemaDemoStringAndChar", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Text column families", "字符串与文本类型", "String & Text Types", "demo:schema text-types", "text-types", "TestSchemaDemoTextTypes", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "UUID and ULID columns", "字符串与文本类型", "String & Text Types", "demo:schema uuid-ulid", "uuid-ulid", "TestSchemaDemoUUIDAndULID", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "IP and MAC address columns", "字符串与文本类型", "String & Text Types", "demo:schema network-addresses", "network-addresses", "TestSchemaDemoNetworkAddresses", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Remember token column", "字符串与文本类型", "String & Text Types", "demo:schema remember-token", "remember-token", "TestSchemaDemoRememberToken", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Boolean columns", "数值类型", "Numeric Types", "demo:schema boolean", "boolean", "TestSchemaDemoBoolean", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Float and double columns", "数值类型", "Numeric Types", "demo:schema floating-point", "floating-point", "TestSchemaDemoFloatingPoint", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Signed and unsigned decimal columns", "数值类型", "Numeric Types", "demo:schema decimal", "decimal", "TestSchemaDemoDecimal", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Date columns", "日期时间类型", "Date & Time Types", "demo:schema date", "date", "TestSchemaDemoDate", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "DateTime columns and timezone alias", "日期时间类型", "Date & Time Types", "demo:schema datetime", "datetime", "TestSchemaDemoDateTime", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Time columns and timezone alias", "日期时间类型", "Date & Time Types", "demo:schema time", "time", "TestSchemaDemoTime", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Timestamp columns and timezone alias", "日期时间类型", "Date & Time Types", "demo:schema timestamp", "timestamp", "TestSchemaDemoTimestamp", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Year columns", "日期时间类型", "Date & Time Types", "demo:schema year", "year", "TestSchemaDemoYear", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Timestamp convenience columns and aliases", "日期时间类型", "Date & Time Types", "demo:schema timestamps", "timestamps", "TestSchemaDemoTimestamps", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Soft-delete columns and timezone alias", "日期时间类型", "Date & Time Types", "demo:schema soft-deletes", "soft-deletes", "TestSchemaDemoSoftDeletes", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Binary columns", "布尔、JSON、二进制、枚举与空间类型", "Boolean, JSON, Binary, Enum & Spatial Types", "demo:schema binary", "binary", "TestSchemaDemoBinary", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "JSON and JSONB columns", "布尔、JSON、二进制、枚举与空间类型", "Boolean, JSON, Binary, Enum & Spatial Types", "demo:schema json", "json", "TestSchemaDemoJSON", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Enum and set columns", "布尔、JSON、二进制、枚举与空间类型", "Boolean, JSON, Binary, Enum & Spatial Types", "demo:schema enum-set", "enum-set", "TestSchemaDemoEnumAndSet", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Geometry, geography, point, line, and polygon columns", "布尔、JSON、二进制、枚举与空间类型", "Boolean, JSON, Binary, Enum & Spatial Types", "demo:schema spatial-types", "spatial-types", "TestSchemaDemoSpatialTypes", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Vector columns", "布尔、JSON、二进制、枚举与空间类型", "Boolean, JSON, Binary, Enum & Spatial Types", "demo:schema vector", "vector", "TestSchemaDemoVector", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Foreign ID columns", "外键 ID 与多态类型", "Foreign ID & Morph Types", "demo:schema foreign-id", "foreign-id", "TestSchemaDemoForeignID", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "ForeignIdFor alias semantics", "外键 ID 与多态类型", "Foreign ID & Morph Types", "demo:schema foreign-id-for", "foreign-id-for", "TestSchemaDemoForeignIDFor", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Polymorphic ID, type, and index columns", "外键 ID 与多态类型", "Foreign ID & Morph Types", "demo:schema morphs", "morphs", "TestSchemaDemoMorphs", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Nullable polymorphic columns", "外键 ID 与多态类型", "Foreign ID & Morph Types", "demo:schema nullable-morphs", "nullable-morphs", "TestSchemaDemoNullableMorphs", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Nullable timestamp convenience alias", "便捷方法", "Convenience Methods", "demo:schema nullable-timestamps", "nullable-timestamps", "TestSchemaDemoNullableTimestamps", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Nullable column modifier", "字段修饰符", "Column Modifiers", "demo:schema nullable", "nullable", "TestSchemaDemoNullable", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Not-null column modifier", "字段修饰符", "Column Modifiers", "demo:schema not-null", "not-null", "TestSchemaDemoNotNull", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Unsigned column modifier", "字段修饰符", "Column Modifiers", "demo:schema unsigned", "unsigned", "TestSchemaDemoUnsigned", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Auto-increment column modifier", "字段修饰符", "Column Modifiers", "demo:schema auto-increment", "auto-increment", "TestSchemaDemoAutoIncrement", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Primary-key column modifier", "字段修饰符", "Column Modifiers", "demo:schema primary-modifier", "primary-modifier", "TestSchemaDemoPrimaryModifier", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Unique index column modifier and removal", "字段修饰符", "Column Modifiers", "demo:schema unique-modifier", "unique-modifier", "TestSchemaDemoUniqueModifier", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Plain index column modifier and removal", "字段修饰符", "Column Modifiers", "demo:schema index-modifier", "index-modifier", "TestSchemaDemoIndexModifier", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Default value modifier and SQL literal handling", "字段修饰符", "Column Modifiers", "demo:schema default", "default", "TestSchemaDemoDefault", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Column comment modifier", "字段修饰符", "Column Modifiers", "demo:schema comment", "comment", "TestSchemaDemoComment", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "First-position column modifier", "字段修饰符", "Column Modifiers", "demo:schema first", "first", "TestSchemaDemoFirst", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "After-position column modifier", "字段修饰符", "Column Modifiers", "demo:schema after", "after", "TestSchemaDemoAfter", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Column character set modifier", "字段修饰符", "Column Modifiers", "demo:schema charset", "charset", "TestSchemaDemoCharset", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Column collation modifier", "字段修饰符", "Column Modifiers", "demo:schema collation", "collation", "TestSchemaDemoCollation", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Current timestamp default modifier", "字段修饰符", "Column Modifiers", "demo:schema use-current", "use-current", "TestSchemaDemoUseCurrent", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Current timestamp update modifier", "字段修饰符", "Column Modifiers", "demo:schema use-current-on-update", "use-current-on-update", "TestSchemaDemoUseCurrentOnUpdate", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Invisible column modifier", "字段修饰符", "Column Modifiers", "demo:schema invisible", "invisible", "TestSchemaDemoInvisible", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Stored generated column placeholder", "字段修饰符", "Column Modifiers", "demo:schema stored-as", "stored-as", "TestSchemaDemoStoredAs", LevelCompile, StatusPlanned),
		baselineEntry("schema", "Virtual generated column placeholder", "字段修饰符", "Column Modifiers", "demo:schema virtual-as", "virtual-as", "TestSchemaDemoVirtualAs", LevelCompile, StatusPlanned),
		baselineEntry("schema", "Laravel From compatibility placeholder", "字段修饰符", "Column Modifiers", "demo:schema from", "from", "TestSchemaDemoFrom", LevelCompile, StatusPlanned),
		baselineEntry("schema", "Laravel Instant compatibility placeholder", "字段修饰符", "Column Modifiers", "demo:schema instant", "instant", "TestSchemaDemoInstant", LevelCompile, StatusPlanned),
		baselineEntry("schema", "Laravel Lock compatibility placeholder", "字段修饰符", "Column Modifiers", "demo:schema lock", "lock", "TestSchemaDemoLock", LevelCompile, StatusPlanned),
		baselineEntry("schema", "Change modifier idempotency responsibility", "修改字段", "Modifying Columns", "demo:schema change-semantics", "change-semantics", "TestSchemaDemoChangeSemantics", LevelCompile, StatusPlanned),
		baselineEntry("schema", "Dropping remember token columns", "删除约定字段", "Dropping Convention Columns", "demo:schema drop-remember-token", "drop-remember-token", "TestSchemaDemoDropRememberToken", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Dropping timestamp columns", "删除约定字段", "Dropping Convention Columns", "demo:schema drop-timestamps", "drop-timestamps", "TestSchemaDemoDropTimestamps", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Dropping timezone timestamp aliases", "删除约定字段", "Dropping Convention Columns", "demo:schema drop-timestamps-tz", "drop-timestamps-tz", "TestSchemaDemoDropTimestampsTz", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Dropping soft-delete columns and indexes", "删除约定字段", "Dropping Convention Columns", "demo:schema drop-soft-deletes", "drop-soft-deletes", "TestSchemaDemoDropSoftDeletes", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Dropping timezone soft-delete aliases", "删除约定字段", "Dropping Convention Columns", "demo:schema drop-soft-deletes-tz", "drop-soft-deletes-tz", "TestSchemaDemoDropSoftDeletesTz", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Dropping polymorphic columns and indexes", "删除约定字段", "Dropping Convention Columns", "demo:schema drop-morphs", "drop-morphs", "TestSchemaDemoDropMorphs", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Dropping constrained foreign IDs", "删除约定字段", "Dropping Convention Columns", "demo:schema drop-constrained-foreign-id", "drop-constrained-foreign-id", "TestSchemaDemoDropConstrainedForeignID", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Dropping foreign ID columns without constraints", "删除约定字段", "Dropping Convention Columns", "demo:schema drop-foreign-id-for", "drop-foreign-id-for", "TestSchemaDemoDropForeignIDFor", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Primary index creation", "创建索引", "Creating Indexes", "demo:schema primary-index", "primary-index", "TestSchemaDemoPrimaryIndex", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Unique index creation", "创建索引", "Creating Indexes", "demo:schema unique-index", "unique-index", "TestSchemaDemoUniqueIndex", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Plain index creation", "创建索引", "Creating Indexes", "demo:schema index", "index", "TestSchemaDemoIndex", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Full-text index creation and SQLite downgrade", "创建索引", "Creating Indexes", "demo:schema fulltext-index", "fulltext-index", "TestSchemaDemoFullTextIndex", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Spatial index creation and SQLite downgrade", "创建索引", "Creating Indexes", "demo:schema spatial-index", "spatial-index", "TestSchemaDemoSpatialIndex", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Explicitly named unique and plain indexes", "创建索引", "Creating Indexes", "demo:schema named-indexes", "named-indexes", "TestSchemaDemoNamedIndexes", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Default index names and MySQL length trimming", "创建索引", "Creating Indexes", "demo:schema index-naming", "index-naming", "TestSchemaDemoIndexNaming", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Index renaming and SQLite boundary", "重命名索引", "Renaming Indexes", "demo:schema rename-index", "rename-index", "TestSchemaDemoRenameIndex", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Plain index dropping", "删除索引", "Dropping Indexes", "demo:schema drop-index", "drop-index", "TestSchemaDemoDropIndex", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Unique index dropping", "删除索引", "Dropping Indexes", "demo:schema drop-unique", "drop-unique", "TestSchemaDemoDropUnique", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Primary index dropping", "删除索引", "Dropping Indexes", "demo:schema drop-primary", "drop-primary", "TestSchemaDemoDropPrimary", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Full-text index dropping", "删除索引", "Dropping Indexes", "demo:schema drop-fulltext", "drop-fulltext", "TestSchemaDemoDropFullText", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Spatial index dropping", "删除索引", "Dropping Indexes", "demo:schema drop-spatial-index", "drop-spatial-index", "TestSchemaDemoDropSpatialIndex", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Convention-based constrained foreign IDs", "创建外键", "Creating Foreign Keys", "demo:schema constrained", "constrained", "TestSchemaDemoConstrained", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Explicit constrained table and column targets", "创建外键", "Creating Foreign Keys", "demo:schema constrained-explicit", "constrained-explicit", "TestSchemaDemoConstrainedExplicit", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Manual foreign key definitions", "创建外键", "Creating Foreign Keys", "demo:schema foreign", "foreign", "TestSchemaDemoForeign", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Custom foreign key update and delete actions", "创建外键", "Creating Foreign Keys", "demo:schema foreign-actions", "foreign-actions", "TestSchemaDemoForeignActions", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Cascade foreign key actions", "创建外键", "Creating Foreign Keys", "demo:schema cascade-actions", "cascade-actions", "TestSchemaDemoCascadeActions", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Restrict foreign key actions", "创建外键", "Creating Foreign Keys", "demo:schema restrict-actions", "restrict-actions", "TestSchemaDemoRestrictActions", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Set-null foreign key actions", "创建外键", "Creating Foreign Keys", "demo:schema null-actions", "null-actions", "TestSchemaDemoNullActions", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "No-action foreign key actions", "创建外键", "Creating Foreign Keys", "demo:schema no-action-actions", "no-action-actions", "TestSchemaDemoNoActionActions", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Custom foreign key constraint names", "创建外键", "Creating Foreign Keys", "demo:schema foreign-name", "foreign-name", "TestSchemaDemoForeignName", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Foreign key SQL dialect boundary", "创建外键", "Creating Foreign Keys", "demo:schema foreign-dialect", "foreign-dialect", "TestSchemaDemoForeignDialect", LevelCompile, StatusPlanned),
		baselineEntry("schema", "Dropping named foreign key constraints", "删除外键", "Dropping Foreign Keys", "demo:schema drop-foreign", "drop-foreign", "TestSchemaDemoDropForeign", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Table and view existence inspection", "表 / 视图 / Schema 检查", "Table / View / Schema Inspection", "demo:schema table-view-existence", "table-view-existence", "TestSchemaDemoTableViewExistence", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Table metadata and filtered listing", "表 / 视图 / Schema 检查", "Table / View / Schema Inspection", "demo:schema tables", "tables", "TestSchemaDemoTables", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Schema-qualified table name listing", "表 / 视图 / Schema 检查", "Table / View / Schema Inspection", "demo:schema table-listing", "table-listing", "TestSchemaDemoTableListing", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "View metadata inspection", "表 / 视图 / Schema 检查", "Table / View / Schema Inspection", "demo:schema views", "views", "TestSchemaDemoViews", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Schema metadata inspection", "表 / 视图 / Schema 检查", "Table / View / Schema Inspection", "demo:schema schemas", "schemas", "TestSchemaDemoSchemas", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "User-defined type metadata inspection", "表 / 视图 / Schema 检查", "Table / View / Schema Inspection", "demo:schema types", "types", "TestSchemaDemoTypes", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Schema filter input variants", "表 / 视图 / Schema 检查", "Table / View / Schema Inspection", "demo:schema schema-filter", "schema-filter", "TestSchemaDemoSchemaFilter", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Single and multiple column existence inspection", "字段检查", "Column Inspection", "demo:schema has-columns", "has-columns", "TestSchemaDemoHasColumns", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Column metadata and name listing", "字段检查", "Column Inspection", "demo:schema columns", "columns", "TestSchemaDemoColumns", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Short and full column type inspection", "字段检查", "Column Inspection", "demo:schema column-type", "column-type", "TestSchemaDemoColumnType", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Index existence by name, columns, and type", "索引检查", "Index Inspection", "demo:schema has-index", "has-index", "TestSchemaDemoHasIndex", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Index metadata and name listing", "索引检查", "Index Inspection", "demo:schema indexes", "indexes", "TestSchemaDemoIndexes", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Foreign key metadata inspection", "外键检查", "Foreign Key Inspection", "demo:schema foreign-keys", "foreign-keys", "TestSchemaDemoForeignKeys", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Metadata structure contracts", "元数据结构类型", "Metadata Structure Types", "demo:schema metadata-types", "metadata-types", "TestSchemaDemoMetadataTypes", LevelCompile, StatusPlanned),
		baselineEntry("schema", "Conditional execution when a column exists", "字段条件", "Column Conditionals", "demo:schema when-has-column", "when-has-column", "TestSchemaDemoWhenHasColumn", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Conditional execution when a column is missing", "字段条件", "Column Conditionals", "demo:schema when-missing-column", "when-missing-column", "TestSchemaDemoWhenMissingColumn", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Conditional execution when an index is missing", "索引条件", "Index Conditionals", "demo:schema when-missing-index", "when-missing-index", "TestSchemaDemoWhenMissingIndex", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "Disabling foreign key constraints", "外键约束开关", "Foreign Key Constraint Toggles", "demo:schema disable-foreign-keys", "disable-foreign-keys", "TestSchemaDemoDisableForeignKeys", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Enabling foreign key constraints", "外键约束开关", "Foreign Key Constraint Toggles", "demo:schema enable-foreign-keys", "enable-foreign-keys", "TestSchemaDemoEnableForeignKeys", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Scoped foreign key constraint disabling and error precedence", "外键约束开关", "Foreign Key Constraint Toggles", "demo:schema without-foreign-keys", "without-foreign-keys", "TestSchemaDemoWithoutForeignKeys", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Foreign key toggle dialect mechanisms", "外键约束开关", "Foreign Key Constraint Toggles", "demo:schema foreign-key-toggle-dialects", "foreign-key-toggle-dialects", "TestSchemaDemoForeignKeyToggleDialects", LevelCompile, StatusPlanned),
		baselineEntry("schema", "MySQL database creation", "数据库与扩展管理", "Database & Extension Management", "demo:schema create-database", "create-database", "TestSchemaDemoCreateDatabase", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "MySQL database dropping", "数据库与扩展管理", "Database & Extension Management", "demo:schema drop-database", "drop-database", "TestSchemaDemoDropDatabase", LevelIntegration, StatusPlanned, "mysql"),
		baselineEntry("schema", "Extension management capability boundary", "数据库与扩展管理", "Database & Extension Management", "demo:schema ensure-extension", "ensure-extension", "TestSchemaDemoEnsureExtension", LevelCompile, StatusPlanned),
		baselineEntry("schema", "Vector extension management shortcut", "数据库与扩展管理", "Database & Extension Management", "demo:schema ensure-vector-extension", "ensure-vector-extension", "TestSchemaDemoEnsureVectorExtension", LevelCompile, StatusPlanned),
		baselineEntry("schema", "Legacy model schema synchronization", "SyncModels 过渡能力", "SyncModels Transition", "demo:schema sync-models", "sync-models", "TestSchemaDemoSyncModels", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "SyncModels create and missing-column behavior", "SyncModels 过渡能力", "SyncModels Transition", "demo:schema sync-models-columns", "sync-models-columns", "TestSchemaDemoSyncModelsColumns", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "SyncModels defaults and MySQL table options", "SyncModels 过渡能力", "SyncModels Transition", "demo:schema sync-models-defaults", "sync-models-defaults", "TestSchemaDemoSyncModelsDefaults", LevelHermetic, StatusPlanned),
		baselineEntry("schema", "SyncModels migration boundaries", "SyncModels 过渡能力", "SyncModels Transition", "demo:schema sync-models-boundaries", "sync-models-boundaries", "TestSchemaDemoSyncModelsBoundaries", LevelCompile, StatusPlanned),
		baselineEntry("schema", "MySQL and SQLite compatibility matrix", "Dialect 兼容性", "Dialect Compatibility", "demo:schema dialect-compatibility", "dialect-compatibility", "TestSchemaDemoDialectCompatibility", LevelCompile, StatusPlanned),
		baselineEntry("schema", "Laravel Schema API mapping", "与 Laravel Schema 的对应关系", "Laravel Schema Mapping", "demo:schema laravel-compatibility", "laravel-compatibility", "TestSchemaDemoLaravelCompatibility", LevelCompile, StatusPlanned),
	}
}
