package catalog

func serviceProviderEntries() []Entry {
	return []Entry{
		baselineEntry("service-provider", "Provider bootstrap architecture", "介绍", "Introduction", "demo:provider architecture", "architecture", "TestProviderDemoArchitecture", LevelCompile, StatusPlanned),
		baselineEntry("service-provider", "ServiceProvider interface contract", "编写服务提供者", "Writing Service Providers", "demo:provider contract", "contract", "TestProviderDemoContract", LevelCompile, StatusPlanned),
		baselineEntry("service-provider", "Register binding-only contract", "Register 方法", "The Register Method", "demo:provider register-contract", "register-contract", "TestProviderDemoRegisterContract", LevelCompile, StatusPlanned),
		baselineEntry("service-provider", "Container access from providers", "Register 方法", "The Register Method", "demo:provider container-access", "container-access", "TestProviderDemoContainerAccess", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Preserving existing container bindings", "Register 方法", "The Register Method", "demo:provider preserve-binding", "preserve-binding", "TestProviderDemoPreserveBinding", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Transient Bind registrations", "容器绑定方法", "Container Binding Methods", "demo:provider bind", "bind", "TestProviderDemoBind", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Shared Singleton registrations", "容器绑定方法", "Container Binding Methods", "demo:provider singleton", "singleton", "TestProviderDemoSingleton", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Constructed Instance registrations", "容器绑定方法", "Container Binding Methods", "demo:provider instance", "instance", "TestProviderDemoInstance", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Binding aliases", "容器绑定方法", "Container Binding Methods", "demo:provider alias", "alias", "TestProviderDemoAlias", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Resource cleanup with WithCloser", "绑定选项", "Binding Options", "demo:provider with-closer", "with-closer", "TestProviderDemoWithCloser", LevelScenario, StatusPlanned),
		baselineEntry("service-provider", "Resource shutdown groups with WithCloseGroup", "绑定选项", "Binding Options", "demo:provider close-group", "close-group", "TestProviderDemoCloseGroup", LevelScenario, StatusPlanned),
		baselineEntry("service-provider", "Boot after all provider registrations", "Boot 方法", "The Boot Method", "demo:provider boot-order", "boot-order", "TestProviderDemoBootOrder", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Resolving services and registering listeners during Boot", "Boot 方法", "The Boot Method", "demo:provider boot-listeners", "boot-listeners", "TestProviderDemoBootListeners", LevelScenario, StatusPlanned),
		baselineEntry("service-provider", "Console command declarations", "声明命令", "Declaring Commands", "demo:provider commands", "commands", "TestProviderDemoCommands", LevelScenario, StatusPlanned),
		baselineEntry("service-provider", "Command instance and factory inputs", "声明命令", "Declaring Commands", "demo:provider command-inputs", "command-inputs", "TestProviderDemoCommandInputs", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Deferred command mounting and validation", "声明命令", "Declaring Commands", "demo:provider command-deferred", "command-deferred", "TestProviderDemoCommandDeferred", LevelScenario, StatusPlanned),
		baselineEntry("service-provider", "Vendor resource publication declarations", "Vendor Publish", "Vendor Publish", "demo:provider publishes", "publishes", "TestProviderDemoPublishes", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Vendor publish mappings and tags", "Vendor Publish", "Vendor Publish", "demo:provider publish-tags", "publish-tags", "TestProviderDemoPublishTags", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Development-only vendor publication", "Vendor Publish", "Vendor Publish", "demo:provider publish-environment", "publish-environment", "TestProviderDemoPublishEnvironment", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Application provider registration", "注册提供者", "Registering Providers", "demo:provider application-registration", "application-registration", "TestProviderDemoApplicationRegistration", LevelCompile, StatusPlanned),
		baselineEntry("service-provider", "Immediate base provider order", "注册提供者", "Registering Providers", "demo:provider base-order", "base-order", "TestProviderDemoBaseOrder", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Automatic default provider order", "注册提供者", "Registering Providers", "demo:provider default-order", "default-order", "TestProviderDemoDefaultOrder", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Extension provider registration and order", "注册提供者", "Registering Providers", "demo:provider extension-order", "extension-order", "TestProviderDemoExtensionOrder", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Application provider declaration order", "注册提供者", "Registering Providers", "demo:provider application-order", "application-order", "TestProviderDemoApplicationOrder", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Explicit NamedProvider identity", "提供者标识", "Provider Identity", "demo:provider named-identity", "named-identity", "TestProviderDemoNamedIdentity", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Implicit provider type identity", "提供者标识", "Provider Identity", "demo:provider implicit-identity", "implicit-identity", "TestProviderDemoImplicitIdentity", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Duplicate provider identity handling", "提供者标识", "Provider Identity", "demo:provider duplicate-identity", "duplicate-identity", "TestProviderDemoDuplicateIdentity", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "DeferrableProvider interface contract", "延迟提供者", "Deferred Providers", "demo:provider deferrable-contract", "deferrable-contract", "TestProviderDemoDeferrableContract", LevelCompile, StatusPlanned),
		baselineEntry("service-provider", "Deferred service key declarations", "延迟提供者", "Deferred Providers", "demo:provider provides", "provides", "TestProviderDemoProvides", LevelCompile, StatusPlanned),
		baselineEntry("service-provider", "Register and Boot on first deferred resolution", "延迟提供者", "Deferred Providers", "demo:provider deferred-resolution", "deferred-resolution", "TestProviderDemoDeferredResolution", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Deferred service map cleanup after provider loading", "延迟提供者", "Deferred Providers", "demo:provider deferred-map-cleanup", "deferred-map-cleanup", "TestProviderDemoDeferredMapCleanup", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Immediate Boot for providers resolved after startup", "延迟提供者", "Deferred Providers", "demo:provider deferred-late-boot", "deferred-late-boot", "TestProviderDemoDeferredLateBoot", LevelScenario, StatusPlanned),
		baselineEntry("service-provider", "Empty deferred service declaration errors", "延迟提供者", "Deferred Providers", "demo:provider deferred-empty", "deferred-empty", "TestProviderDemoDeferredEmpty", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Deferred service key conflict errors", "延迟提供者", "Deferred Providers", "demo:provider deferred-conflict", "deferred-conflict", "TestProviderDemoDeferredConflict", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Unloaded deferred providers excluded from termination", "延迟提供者", "Deferred Providers", "demo:provider deferred-termination", "deferred-termination", "TestProviderDemoDeferredTermination", LevelScenario, StatusPlanned),
		baselineEntry("service-provider", "TerminableProvider interface contract", "可终止提供者", "Terminable Providers", "demo:provider terminable-contract", "terminable-contract", "TestProviderDemoTerminableContract", LevelCompile, StatusPlanned),
		baselineEntry("service-provider", "Worker startup and graceful drain lifecycle", "可终止提供者", "Terminable Providers", "demo:provider worker-lifecycle", "worker-lifecycle", "TestProviderDemoWorkerLifecycle", LevelScenario, StatusPlanned),
		baselineEntry("service-provider", "Reverse registration order termination", "可终止提供者", "Terminable Providers", "demo:provider terminate-order", "terminate-order", "TestProviderDemoTerminateOrder", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Termination eligibility after successful Register", "可终止提供者", "Terminable Providers", "demo:provider terminate-eligibility", "terminate-eligibility", "TestProviderDemoTerminateEligibility", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Shutdown context propagation to Terminate", "可终止提供者", "Terminable Providers", "demo:provider terminate-context", "terminate-context", "TestProviderDemoTerminateContext", LevelScenario, StatusPlanned),
		baselineEntry("service-provider", "Container closers run after provider termination", "可终止提供者", "Terminable Providers", "demo:provider closer-order", "closer-order", "TestProviderDemoCloserOrder", LevelHermetic, StatusPlanned),
		baselineEntry("service-provider", "Combined deferred and terminable provider lifecycle", "可终止提供者", "Terminable Providers", "demo:provider full-lifecycle", "full-lifecycle", "TestProviderDemoFullLifecycle", LevelScenario, StatusPlanned),
	}
}
