package catalog

func sessionEntries() []Entry {
	return []Entry{
		baselineEntry("session", "Manager, Store, and server-side payload architecture", "简介", "Introduction", "demo:session architecture", "architecture", "TestSessionDemoArchitecture", LevelCompile, StatusPlanned),
		baselineEntry("session", "Environment-backed session configuration", "配置文件", "Config File", "demo:session config", "config", "TestSessionDemoConfig", LevelHermetic, StatusPlanned),
		baselineEntry("session", "File driver prerequisites and persistence", "File", "File", "demo:session file-driver", "file-driver", "TestSessionDemoFileDriver", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Redis connection prerequisites and shared storage", "Redis", "Redis", "demo:session redis-driver --connection=redis", "redis-driver", "TestSessionDemoRedisDriver", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("session", "Driver, lifetime, expiration, encryption, and encoding configuration", "顶层配置", "Top-Level Configuration", "demo:session top-level-config", "top-level-config", "TestSessionDemoTopLevelConfig", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Cookie name, scope, security, and SameSite configuration", "Cookie 配置", "Cookie Configuration", "demo:session cookie-config", "cookie-config", "TestSessionDemoCookieConfig", LevelHermetic, StatusPlanned),
		baselineEntry("session", "File storage directory configuration", "File Driver 配置", "File Driver Configuration", "demo:session file-config", "file-config", "TestSessionDemoFileConfig", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Redis connection and key prefix configuration", "Redis Driver 配置", "Redis Driver Configuration", "demo:session redis-config", "redis-config", "TestSessionDemoRedisConfig", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Lock hold and wait configuration", "锁配置", "Lock Configuration", "demo:session lock-config", "lock-config", "TestSessionDemoLockConfig", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Explicit DefaultConfig and NewManager construction", "配置参数", "Configuration Parameters", "demo:session manager-config", "manager-config", "TestSessionDemoManagerConfig", LevelHermetic, StatusPlanned),
		baselineEntry("session", "StartSession request restore, save, and response lifecycle", "中间件", "Middleware", "demo:session middleware", "middleware", "TestSessionDemoMiddleware", LevelScenario, StatusPlanned),
		baselineEntry("session", "Missing, expired, malformed, and invalid ID recovery", "中间件", "Middleware", "demo:session recovery", "recovery", "TestSessionDemoRecovery", LevelScenario, StatusPlanned),
		baselineEntry("session", "Response buffering and streaming-route limitation", "中间件", "Middleware", "demo:session response-buffering", "response-buffering", "TestSessionDemoResponseBuffering", LevelScenario, StatusPlanned),
		baselineEntry("session", "Request-scoped StoreFrom and facade access", "中间件", "Middleware", "demo:session store-from", "store-from", "TestSessionDemoStoreFrom", LevelScenario, StatusPlanned),
		baselineEntry("session", "WithManager injection and default manager resolution", "使用自定义 Manager", "Using a Custom Manager", "demo:session custom-manager", "custom-manager", "TestSessionDemoCustomManager", LevelScenario, StatusPlanned),
		baselineEntry("session", "Get fallback and missing-key behavior", "基本读取", "Basic Retrieval", "demo:session get", "get", "TestSessionDemoGet", LevelHermetic, StatusPlanned),
		baselineEntry("session", "All returns an isolated shallow map copy", "读取所有 Session 数据", "Retrieving All Session Data", "demo:session all", "all", "TestSessionDemoAll", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Only and Except data subsets", "读取部分 Session 数据", "Retrieving a Portion of the Session Data", "demo:session subsets", "subsets", "TestSessionDemoSubsets", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Has excludes nil values", "判断 Session 中是否存在某个 Key", "Determining If an Item Exists in the Session", "demo:session has", "has", "TestSessionDemoHas", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Exists includes nil values", "判断 Session 中是否存在某个 Key", "Determining If an Item Exists in the Session", "demo:session exists", "exists", "TestSessionDemoExists", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Missing detects absent keys", "判断 Session 中是否存在某个 Key", "Determining If an Item Exists in the Session", "demo:session missing", "missing", "TestSessionDemoMissing", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Put serializable session values", "基本写入", "Basic Storage", "demo:session put", "put", "TestSessionDemoPut", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Increment and Decrement integer values and reject invalid numbers", "递增与递减 Session 值", "Incrementing and Decrementing Session Values", "demo:session counters", "counters", "TestSessionDemoCounters", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Flash current and next request lifecycle", "`Flash(key string, value any)`", "`Flash(key string, value any)`", "demo:session flash", "flash", "TestSessionDemoFlash", LevelScenario, StatusPlanned),
		baselineEntry("session", "Now current-request-only flash values", "`Now(key string, value any)`", "`Now(key string, value any)`", "demo:session now", "now", "TestSessionDemoNow", LevelScenario, StatusPlanned),
		baselineEntry("session", "Reflash extends all current flash values", "`Reflash()`", "`Reflash()`", "demo:session reflash", "reflash", "TestSessionDemoReflash", LevelScenario, StatusPlanned),
		baselineEntry("session", "Keep extends selected flash keys", "`Keep(keys ...string)`", "`Keep(keys ...string)`", "demo:session keep", "keep", "TestSessionDemoKeep", LevelScenario, StatusPlanned),
		baselineEntry("session", "Forget one or multiple session keys", "`Forget(keys ...string)`", "`Forget(keys ...string)`", "demo:session forget", "forget", "TestSessionDemoForget", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Flush data and flash metadata without changing the ID", "`Flush()`", "`Flush()`", "demo:session flush", "flush", "TestSessionDemoFlush", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Pull with fallback and flash metadata cleanup", "`Pull(key string, def ...any) any`", "`Pull(key string, def ...any) any`", "demo:session pull", "pull", "TestSessionDemoPull", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Regenerate retains data and destroys the old ID", "`Regenerate(ctx context.Context) error`", "`Regenerate(ctx context.Context) error`", "demo:session regenerate", "regenerate", "TestSessionDemoRegenerate", LevelScenario, StatusPlanned),
		baselineEntry("session", "Invalidate clears data and rotates the ID", "`Invalidate(ctx context.Context) error`", "`Invalidate(ctx context.Context) error`", "demo:session invalidate", "invalidate", "TestSessionDemoInvalidate", LevelScenario, StatusPlanned),
		baselineEntry("session", "Concurrent same-ID requests and lock timeout", "Session 阻塞", "Session Blocking", "demo:session blocking", "blocking", "TestSessionDemoBlocking", LevelScenario, StatusPlanned),
		baselineEntry("session", "File lock token, expiration, and release", "Session 阻塞", "Session Blocking", "demo:session file-lock", "file-lock", "TestSessionDemoFileLock", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Redis lock ownership and expiration", "Session 阻塞", "Session Blocking", "demo:session redis-lock --connection=redis", "redis-lock", "TestSessionDemoRedisLock", LevelIntegration, StatusPlanned, "redis"),
		baselineEntry("session", "Session ID Cookie attributes and server-side lifetime", "Cookie 处理", "Cookie Handling", "demo:session id-cookie", "id-cookie", "TestSessionDemoIDCookie", LevelScenario, StatusPlanned),
		baselineEntry("session", "Expire-on-close omits browser Cookie expiry only", "Cookie 处理", "Cookie Handling", "demo:session expire-on-close", "expire-on-close", "TestSessionDemoExpireOnClose", LevelScenario, StatusPlanned),
		baselineEntry("session", "Queued business cookies flush after session Cookie", "Cookie 处理", "Cookie Handling", "demo:session queued-cookies", "queued-cookies", "TestSessionDemoQueuedCookies", LevelScenario, StatusPlanned),
		baselineEntry("session", "Session payload encryption leaves the ID Cookie opaque", "加密", "Encryption", "demo:session encryption", "encryption", "TestSessionDemoEncryption", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Encryptor interface and NopEncryptor behavior", "加密", "Encryption", "demo:session encryptor", "encryptor", "TestSessionDemoEncryptor", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Custom Encryptor injection", "加密", "Encryption", "demo:session custom-encryptor", "custom-encryptor", "TestSessionDemoCustomEncryptor", LevelHermetic, StatusPlanned),
		baselineEntry("session", "SensitiveError redacts encryption and decryption failures", "加密", "Encryption", "demo:session sensitive-error", "sensitive-error", "TestSessionDemoSensitiveError", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Driver Read, Write, Destroy, and GC contract", "实现 Driver", "Implementing the Driver", "demo:session driver-contract", "driver-contract", "TestSessionDemoDriverContract", LevelCompile, StatusPlanned),
		baselineEntry("session", "Optional Locker and Lock.Release contracts", "实现 Driver", "Implementing the Driver", "demo:session locker-contract", "locker-contract", "TestSessionDemoLockerContract", LevelCompile, StatusPlanned),
		baselineEntry("session", "Extend registration before manager resolution", "注册 Driver", "Registering the Driver", "demo:session extend", "extend", "TestSessionDemoExtend", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Duplicate and invalid driver registration", "注册 Driver", "Registering the Driver", "demo:session extend-validation", "extend-validation", "TestSessionDemoExtendValidation", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Unknown driver returns ErrDriverNotFound", "注册 Driver", "Registering the Driver", "demo:session unknown-driver", "unknown-driver", "TestSessionDemoUnknownDriver", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Session error constants and error classification", "错误常量", "Error Constants", "demo:session errors", "errors", "TestSessionDemoErrors", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Recoverable read errors start a fresh session", "错误常量", "Error Constants", "demo:session recoverable-errors", "recoverable-errors", "TestSessionDemoRecoverableErrors", LevelHermetic, StatusPlanned),
		baselineEntry("session", "Laravel session API and blocking correspondence", "与 Laravel Session 的对应关系", "Laravel Session Mapping", "demo:session laravel-compatibility", "laravel-compatibility", "TestSessionDemoLaravelCompatibility", LevelCompile, StatusPlanned),
	}
}
