package catalog

func timerEntries() []Entry {
	return []Entry{
		baselineEntry("timer", "Scheduler architecture", "简介", "Introduction", "demo:timer architecture", "architecture", "TestTimerDemoArchitecture", LevelCompile, StatusImplemented),
		baselineEntry("timer", "Long-running process requirements", "环境要求", "Requirements", "demo:timer requirements", "requirements", "TestTimerDemoRequirements", LevelCompile, StatusImplemented),
		baselineEntry("timer", "Cron command startup", "启动命令", "Start Command", "demo:timer cron-command", "cron-command", "TestTimerDemoCronCommand", LevelScenario, StatusImplemented),
		baselineEntry("timer", "Signal-driven graceful shutdown", "停止调度器", "Stopping The Scheduler", "demo:timer signal-shutdown", "signal-shutdown", "TestTimerDemoSignalShutdown", LevelScenario, StatusImplemented),
		baselineEntry("timer", "Application schedule registration", "注册任务", "Registering Tasks", "demo:timer registration", "registration", "TestTimerDemoRegistration", LevelCompile, StatusImplemented),
		baselineEntry("timer", "Process manager deployment", "生产环境部署", "Production Deployment", "demo:timer deployment", "deployment", "TestTimerDemoDeployment", LevelCompile, StatusImplemented),
		baselineEntry("timer", "Local timezone scheduling", "配置", "Configuration", "demo:timer timezone", "timezone", "TestTimerDemoTimezone", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Debug success logging", "配置", "Configuration", "demo:timer debug-logging", "debug-logging", "TestTimerDemoDebugLogging", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Overlap cache configuration", "配置", "Configuration", "demo:timer overlap-cache", "overlap-cache", "TestTimerDemoOverlapCacheConfiguration", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Exception reporter configuration", "配置", "Configuration", "demo:timer exception-config", "exception-config", "TestTimerDemoExceptionConfiguration", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Command task registration", "通过命令签名注册", "Registering Commands By Signature", "demo:timer command", "command", "TestTimerDemoCommand", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Command signature and resolver validation", "通过命令签名注册", "Registering Commands By Signature", "demo:timer command-validation", "command-validation", "TestTimerDemoCommandValidation", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Closure task registration", "通过闭包注册", "Registering Closures", "demo:timer call", "call", "TestTimerDemoCall", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Fixed duration intervals", "固定间隔", "Fixed Intervals", "demo:timer every", "every", "TestTimerDemoEvery", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Second-level frequency helpers", "秒级调度", "Second-Level Scheduling", "demo:timer second-frequencies", "second-frequencies", "TestTimerDemoSecondFrequencies", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Minute-level frequency helpers", "分钟级调度", "Minute-Level Scheduling", "demo:timer minute-frequencies", "minute-frequencies", "TestTimerDemoMinuteFrequencies", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Hourly scheduling", "小时级调度", "Hourly Scheduling", "demo:timer hourly", "hourly", "TestTimerDemoHourly", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Hourly minute offsets", "小时级调度", "Hourly Scheduling", "demo:timer hourly-at", "hourly-at", "TestTimerDemoHourlyAt", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Odd and stepped-hour scheduling", "小时级调度", "Hourly Scheduling", "demo:timer hour-steps", "hour-steps", "TestTimerDemoHourSteps", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Daily scheduling", "每日调度", "Daily Scheduling", "demo:timer daily", "daily", "TestTimerDemoDaily", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Daily scheduling at a time", "每日调度", "Daily Scheduling", "demo:timer daily-at", "daily-at", "TestTimerDemoDailyAt", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Twice-daily hour scheduling", "每日调度", "Daily Scheduling", "demo:timer twice-daily", "twice-daily", "TestTimerDemoTwiceDaily", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Twice-daily time scheduling", "每日调度", "Daily Scheduling", "demo:timer twice-daily-at", "twice-daily-at", "TestTimerDemoTwiceDailyAt", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Composable hit time", "`At(timeValue)` — 设置命中时间", "`At(timeValue)` - Set The Hit Time", "demo:timer at", "at", "TestTimerDemoAt", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Weekly scheduling", "每周调度", "Weekly Scheduling", "demo:timer weekly", "weekly", "TestTimerDemoWeekly", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Weekly day and time scheduling", "`WeeklyOn(dayOfWeek, timeValue...)`", "`WeeklyOn(dayOfWeek, timeValue...)`", "demo:timer weekly-on", "weekly-on", "TestTimerDemoWeeklyOn", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Weekday and weekend constraints", "每周调度", "Weekly Scheduling", "demo:timer weekday-groups", "weekday-groups", "TestTimerDemoWeekdayGroups", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Named weekday constraints", "每周调度", "Weekly Scheduling", "demo:timer named-weekdays", "named-weekdays", "TestTimerDemoNamedWeekdays", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Custom weekday constraints", "`Days(days)` — 自定义星期", "`Days(days)` - Custom Weekdays", "demo:timer days", "days", "TestTimerDemoDays", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Monthly scheduling", "每月调度", "Monthly Scheduling", "demo:timer monthly", "monthly", "TestTimerDemoMonthly", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Monthly day and time scheduling", "`MonthlyOn(dayOfMonth, timeValue...)`", "`MonthlyOn(dayOfMonth, timeValue...)`", "demo:timer monthly-on", "monthly-on", "TestTimerDemoMonthlyOn", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Twice-monthly scheduling", "`TwiceMonthly(args...)`", "`TwiceMonthly(args...)`", "demo:timer twice-monthly", "twice-monthly", "TestTimerDemoTwiceMonthly", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Last day of month scheduling", "`LastDayOfMonth(timeValue...)`", "`LastDayOfMonth(timeValue...)`", "demo:timer last-day-of-month", "last-day-of-month", "TestTimerDemoLastDayOfMonth", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Multiple days of month constraints", "`DaysOfMonth(days...)`", "`DaysOfMonth(days...)`", "demo:timer days-of-month", "days-of-month", "TestTimerDemoDaysOfMonth", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Quarterly scheduling", "季度 / 年度调度", "Quarterly / Yearly Scheduling", "demo:timer quarterly", "quarterly", "TestTimerDemoQuarterly", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Quarter-relative day scheduling", "`QuarterlyOn(args...)`", "`QuarterlyOn(args...)`", "demo:timer quarterly-on", "quarterly-on", "TestTimerDemoQuarterlyOn", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Yearly scheduling", "季度 / 年度调度", "Quarterly / Yearly Scheduling", "demo:timer yearly", "yearly", "TestTimerDemoYearly", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Yearly month, day, and time scheduling", "`YearlyOn(args...)`", "`YearlyOn(args...)`", "demo:timer yearly-on", "yearly-on", "TestTimerDemoYearlyOn", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Overlapping task prevention", "防重叠执行", "Preventing Overlapping Runs", "demo:timer without-overlapping", "without-overlapping", "TestTimerDemoWithoutOverlapping", LevelScenario, StatusImplemented),
		baselineEntry("timer", "Cross-process overlap prevention", "防重叠执行", "Preventing Overlapping Runs", "demo:timer cross-process-overlap --connection=redis", "cross-process-overlap", "TestTimerDemoCrossProcessOverlap", LevelIntegration, StatusImplemented, "redis"),
		baselineEntry("timer", "Scheduler start lifecycle", "`Start(ctx)` — 启动调度", "`Start(ctx)` - Start Scheduling", "demo:timer start", "start", "TestTimerDemoStart", LevelScenario, StatusImplemented),
		baselineEntry("timer", "Scheduler stop lifecycle", "`Stop()` — 停止调度", "`Stop()` - Stop Scheduling", "demo:timer stop", "stop", "TestTimerDemoStop", LevelScenario, StatusImplemented),
		baselineEntry("timer", "Registered task summary", "查看已注册任务", "Inspecting Registered Tasks", "demo:timer summary", "summary", "TestTimerDemoSummary", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Task error isolation and reporting", "任务返回 error", "Task Returns An Error", "demo:timer task-error", "task-error", "TestTimerDemoTaskError", LevelScenario, StatusImplemented),
		baselineEntry("timer", "Task panic isolation and reporting", "任务 panic", "Task Panics", "demo:timer task-panic", "task-panic", "TestTimerDemoTaskPanic", LevelScenario, StatusImplemented),
		baselineEntry("timer", "Successful task debug output", "任务成功执行", "Task Runs Successfully", "demo:timer task-success", "task-success", "TestTimerDemoTaskSuccess", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Exception Reporter dependency", "异常上报依赖", "Exception Reporting Dependency", "demo:timer exception-reporter", "exception-reporter", "TestTimerDemoExceptionReporter", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Fixed interval execution model", "两种调度模式", "Two Scheduling Modes", "demo:timer fixed-interval-model", "fixed-interval-model", "TestTimerDemoFixedIntervalModel", LevelScenario, StatusImplemented),
		baselineEntry("timer", "Calendar execution model", "两种调度模式", "Two Scheduling Modes", "demo:timer calendar-model", "calendar-model", "TestTimerDemoCalendarModel", LevelScenario, StatusImplemented),
		baselineEntry("timer", "Immediate run compatibility", "启动时立即执行", "Immediate Run On Startup", "demo:timer immediate-run", "immediate-run", "TestTimerDemoImmediateRun", LevelScenario, StatusImplemented),
		baselineEntry("timer", "Parallel tasks and serial task runs", "并发与串行", "Parallel and Serial Execution", "demo:timer execution-concurrency", "execution-concurrency", "TestTimerDemoExecutionConcurrency", LevelScenario, StatusImplemented),
		baselineEntry("timer", "Time string parsing and validation", "时间字符串", "Time Strings", "demo:timer time-parsing", "time-parsing", "TestTimerDemoTimeParsing", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Minute and hour list parsing", "分钟和小时列表", "Minute and Hour Lists", "demo:timer offset-parsing", "offset-parsing", "TestTimerDemoOffsetParsing", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Weekday value parsing", "星期值", "Weekday Values", "demo:timer weekday-parsing", "weekday-parsing", "TestTimerDemoWeekdayParsing", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Legacy Timer interval type", "Timer 基础类型", "Timer Base Types", "demo:timer timer-type", "timer-type", "TestTimerDemoTimerType", LevelCompile, StatusImplemented),
		baselineEntry("timer", "ResolvedCommand bridge contract", "ResolvedCommand", "ResolvedCommand", "demo:timer resolved-command", "resolved-command", "TestTimerDemoResolvedCommand", LevelCompile, StatusImplemented),
		baselineEntry("timer", "CommandResolver contract and injection", "CommandResolver", "CommandResolver", "demo:timer command-resolver", "command-resolver", "TestTimerDemoCommandResolver", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Standalone Schedule construction", "NewSchedule", "NewSchedule", "demo:timer new-schedule", "new-schedule", "TestTimerDemoNewSchedule", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Scheduled task naming", "ScheduledTask 元信息方法", "ScheduledTask Metadata Methods", "demo:timer name", "name", "TestTimerDemoName", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Scheduled task descriptions", "ScheduledTask 元信息方法", "ScheduledTask Metadata Methods", "demo:timer description", "description", "TestTimerDemoDescription", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Scheduled task defaults", "默认配置", "Defaults", "demo:timer defaults", "defaults", "TestTimerDemoDefaults", LevelHermetic, StatusImplemented),
		baselineEntry("timer", "Independent scheduler usage", "独立使用调度器（不走 Console Kernel）", "Using The Scheduler Independently Without The Console Kernel", "demo:timer standalone", "standalone", "TestTimerDemoStandalone", LevelScenario, StatusImplemented),
	}
}
